### ISSUE TITLE
Allow to ignore optional query variables (with fragments)

### ISSUE THREAD

**Issue by arunoda** [facebook/graphql#103]
For an example, have a look at following query:

~~~js
query postAndComments($postCount: Int!) {
  getRecentPosts(count: $postCount) {
    title,
    content,
    ...comments
  }
}

fragment comments on Post {
  comments(limit: $commentLimit) {
    content,
    timestamp
  }
}
~~~

Now this throws an error:

~~~json
{
  "errors": [
    {
      "message": "Variable \"$commentLimit\" is not defined by operation \"postAndComments\"."
    }
  ]
}
~~~

If we allow to this, I think it'd be great. Here's the use case.

With this, I can use `comments` fragments in queries where `commentLimit` query variable does not exists as well.

What you guys think about this?

**Comment by leebyron** [comment]
I'm a bit confused about your proposal. The concern that this validation error is reporting is that you're using a variable which hasn't been defined. This is very often the result of programmer-error where a variable was spelled incorrectly or added to a fragment but forgot to be defined.

**Comment by arunoda** [comment]
Yeah. I get it. 
We can always define it and send a null a value. 

I am gonna close this.
