### ISSUE TITLE
Pagination algorithm is not comprehensive

### ISSUE THREAD

**Issue by vslinko** [facebook/graphql#104]
I'm trying to implement pagination algorithm for my data and I don't know how to handle cases when `first ` and `last` are negative.

What is your opinion about this?

ref: https://facebook.github.io/relay/graphql/connections.htm#sec-Pagination-algorithm

**Comment by AndrewIngram** [comment]
Should this issue be on Relay instead? Pagination is a Relay feature, not GraphQL

**Comment by leebyron** [comment]
I believe `first` and `last` assume positive integers. They should probably throw errors if they're negative. But I agree that you should take this up with https://github.com/facebook/relay
