### ISSUE TITLE
Spec "Validation" section title "Operations" repeated, breaks TOC

### ISSUE THREAD

**Issue by bruce** [facebook/graphql#132]
First noticed here: https://facebook.github.io/graphql, and also seen in the Markdown source.

Sections 5.1 and 5.7 have the same name ("Operations") under "Validation" (at the same depth) causing TOC linking to fail.

Consider re-titling 5.7 "Variables," and removing a level of depth. Section 5.7.1 is the only child of 5.7, and 5.7 doesn't contain any overview text before 5.7.1 starts.

**Comment by bruce** [comment]
Worth noting that this issue make deep linking to this section from implementation documentation difficult.

**Comment by leebyron** [comment]
Thanks for the report. spec-md should really be detecting this and produce more specific links. I will investigate.

**Comment by leebyron** [comment]
Now fixed by #129!
