### ISSUE TITLE
field type must be Output Type but got: undefined

### ISSUE THREAD

**Issue by raineroviir** [facebook/graphql#143]
`Root.viewer field type must be Output Type but got: undefined.`

here is my code for the `root.viewer`

```
const RootQuery = new GraphQLObjectType({
  name: 'Root',
  fields: () => ({
    viewer: {
      type: GraphQLUser,
      resolve: () => getViewer()
    }
  })
});
```

I'm figuring I'm defining the type of the field with GraphQLUser but I'm just slightly confused on what GraphQL wants here

**Comment by eugenehp** [comment]
Hey @raineroviir 

You want to use `resolve` in your mutations.
And while you define just type itself, there is no need in `resolve` parameter under your `viewer`.
