### ISSUE TITLE
Problem with special characters

### ISSUE THREAD

**Issue by srinadhK** [facebook/graphql#148]
Hi i want to send "" or \n and some special characters by using GraphQL. what is the best way to do this.

**Comment by dylanahsmith** [comment]
Literal String values can be escaped as described in the [String Value section of the specification](http://facebook.github.io/graphql/#sec-String-Value).

**Comment by leebyron** [comment]
Yes, our String literals are identical to String literals in JSON, and we also use a preceding slash as an escape. So you can send a literal new line character with `"\n"` or a quote character with `"\""`
