### ISSUE TITLE
Common DSL and file type for schema definitions? 

### ISSUE THREAD

**Issue by andye2004** [facebook/graphql#149]
This is more a comment / to provoke discussion rather than an issue but I just wasn't sure where to put it.

I've been looking at GraphQL for a little over a week now and having spent some time looking at how schemas are declared/defined in different implementations it strikes me that some are much easier to read and understand than others. For instance the Javascript examples provided by FB are very easy to read and understand but the corresponding Java implementation is much more difficult to read.

Now I have nothing against GraphQL-Java, in fact I plan on using this for a demonstration project within my organisation, but the complexity of reading the schema generation code led me to think that in an ideal world there would be a single way to define a schema and and it's constituent components. A GraphQL DSL, if you like, and have a common file type to save these into.

For arguments sake, the DSL could simply be Javascript but saved with an alternative file extension. I would be interest to know other peoples thoughts on this?

**Comment by leebyron** [comment]
We're working on an IDL DSL language for types now - you can find the work in progress at #90

**Comment by andye2004** [comment]
Nice one, thanks Lee. Clearly missed that while searching.
