### ISSUE TITLE
Incorrect Input Coercion for Non-Null types

### ISSUE THREAD

**Issue by kolpax** [facebook/graphql#15]
Very fascinating read! Thank you for open-sourcing :)

Looks like the _Input Coercion_ paragraph of Non-Null types in [Section 3 -- Type System](https://github.com/facebook/graphql/blob/master/Section%203%20--%20Type%20System.md#non-null) has incorrectly been copied from the section right above about Lists.

**Comment by dschafer** [comment]
Good catch! We'll make sure to fix this!
