### ISSUE TITLE
Why doesn't GraphQLID auto-gen global UUIDs?

### ISSUE THREAD

**Issue by kevinSuttle** [facebook/graphql#161]
Wondering why we need Relay for this. 

https://github.com/graphql/swapi-graphql/blob/master/src/schema/types/person.js#L18

**Comment by dschafer** [comment]
Not every client will want GraphQLID's to be global UUIDs; people might have autoincrementing integers in their tables, or another ID scheme. GraphQLID is unopinionated about that to allow different implementations to use different approaches.

The spec goes into a bit more detail about ID types at http://facebook.github.io/graphql/#sec-ID - IDs are simply arbitrary strings, but using the ID type hints to the API consumer that this is an identifier.

The `id` field as defined in the https://facebook.github.io/relay/docs/graphql-object-identification.html#content for Relay has particular requirements; that the IDs are globally unique, and that given that ID, we can refetch the object. `globalIdField` is designed to easily take a type and a type-specific ID and generate such a globally-unique ID.

Hope this helps!
