### ISSUE TITLE
how to represent a multivalue key on the query line?

### ISSUE THREAD

**Issue by nguyenm100** [facebook/graphql#166]
I have a table that's used primarily as a lookup map.  Its unique "key" is made up of 3 different fields in the table.  How do I represent that on the query line?  Should it be stitched together on the 'id' as in:

{ foo(id:"keypart1,keypart2,keypart3") }

or is it listed separately on one line

{ foo (field1:keypart1, field2:keypart2, field3:keypart3) }

or hierarchical

{ field1 (id:keypart1) { field2 (id:keypart2) { field3 (id:keypart3) { } } } }

thanks!

**Comment by helfer** [comment]
You should probably create an input type that requires these three fields. Concatenating strings isn't necessarily safe, because making sure that the separator (,) doesn't occur in any of the subparts isn't that easy to do.

Here's what it would look like with an input type:
```
input MultipartKey {
  a: String
  b: String
  c: String
}
```

**Comment by nguyenm100** [comment]
Ok thanks. A bit confused confused when we should use the argument: "id".  According to the spec, it's a scalar of type string but in the case of a multipart key, we should use something else?

**Comment by dylanahsmith** [comment]
An id type is useful for providing an opaque identifier that the server can return to the client to identify an object then the client can use to refer back to the object.  In that case the client wouldn't need to worry about stitching the id together from components.

If that pattern isn't suitable for your use case, then just use multiple arguments or an input type based on your needs.  Or support both (by adding an additional id field) if you need compatibility with a library like relay that uses the id to reload the object.

**Comment by nguyenm100** [comment]
Ok thanks everyone.
