### ISSUE TITLE
Alternative JSON-like syntax?

### ISSUE THREAD

**Issue by freddi301** [facebook/graphql#170]
Hi,
It could be added an ordinary JSON representation for queries? For example, instead of

```
{
  user(id: "1") {
    name
  }
}
```

```
{
  user: { $:{ id: "1" },
    name: true
  }
}
```

It's not horribly much verbose and easier to work with in JavaScript

**Comment by dschafer** [comment]
@leebyron commented on why we ended up going the query language route in #115
