### ISSUE TITLE
Nullability of lists

### ISSUE THREAD

**Issue by jnicklas** [facebook/graphql#171]
I am trying to implement a compliant server, but there is one point that I'm not quite clear on, and I *think* that the spec does not actually clarify it. Apologies if this has been asked before, but google didn't turn up anything useful.

My question is whether elements in a list of a result are allowed to be nullable. That is if I have a type definition like this:

``` graphql
type Post {
  tags: [String]
}
```

Can a server return a result like this:

```
["Foo", null, "Bar"]
```

From reading the spec, I think the answer is "Yes", but I'm not entirely sure. I think that if I wanted to make sure that the list only contains non-null values, I would have to define it with a type of `[String!]`. Or even `[String!]!` if I want to make sure the list itself is not nullable.

If `null` values are *not* allowed inside lists, we run into an odd situation where `[String!]` wouldn't be a valid type, or rather `[String!] == [String]` which is also very strange.

On the other hand, from a client's perspective it feels rather odd that any list could contain a bunch of values which are `null`, and I would expect that this is a mistake that GraphQL clients will make frequently.

**Comment by dylanahsmith** [comment]
Yes, a list can contain null values.

That can be useful when fetching multiple objects by id with a query like `users(ids: $ids) { name }` where the order of the result array would match the order of the ids array argument to correlate the input to the output.  In that case, there would be null values in the result if an id is specified in the input for an object that no longer exists.

A null value for a list I haven't found common, but we have found at least one case where we thought it was appropriate to distinguish between no list and an empty list.

**Comment by stubailo** [comment]
I feel like all four of the following are different and important to have:

```
[String]
[String!]
[String]!
[String!]!
```

The default in GraphQL is that everything is nullable, so it makes sense that by default the list itself and the items inside could be null; given that, I think it should be possible to represent both a list that could be null itself, and a list that could contain null values.

**Comment by leebyron** [comment]
@stubailo nailed it.
