### ISSUE TITLE
Why disallow empty subselections on object types

### ISSUE THREAD

**Issue by opatut** [facebook/graphql#176]
Currently, subselections are *disallowed* on scalars, and *required* on object types.

However, if the API provides a mutation with an object return type, but the user is not interested in the result, they must still query at least one field (chosen at random). That means the user is forced to query data they didn't want in the first place -- kind of contrary to the idea behind graphql.

We could instead distinguish between correct object type vs. scalar usage by requiring **existence** of a subselection on an object type, instead of **non-emptiness**. Look at those mutations:

```graphql
mutation foo {
  mutateSomething(withArg: 12)     # bad
  mutateSomething(withArg: 12) {}  # good
}
```

This could also work on queries: one might want to know whether some object exists, but none of its contents. 

```graphql
query bar {
  myObjectField     # bad
  myObjectField {}  # good
}
```

In the query example, `myObjectField{}` would resolve to one of `{}` or `null`, depending on whether the field resolves to an object or not. And `{}` is a truthy value while `null` is falsy.

PS: I am guessing this was already discussed somewhere, if so, please point me at it -- I cannot find the reasoning behind the design decision.

**Comment by hepin1989** [comment]
or we could implement a new directive like `@omit` for ignore the result.

**Comment by leebyron** [comment]
Thanks for bringing this up again. The spec describes this as it does to avoid mistakes in queries, but I think it's worth further discussion.

The few times this has come up before, it's always been in the context of mutations and not caring about the response of the mutation. In those cases you work around by writing `{ __typename }` if you truly don't care about the result, but more often than not we find that this was a theoretical concern and in practice you almost always want *something* from the mutation, even if it's just the `id` of the thing that was mutated.

I'm curious if there are real cases that have come up in the context of queries where you only want to know of an object-field existance but not know anything else about it.

One maybe nice thing about disallowing `{}` is that if you're maintaining or refactoring a query and notice that the last field in a `{ ... }` should be removed, then you know that you can also remove the parent field as well.

I'm curious for more opinions on this topic.

**Comment by RyanCCollins** [comment]
I like the idea of having an @omit directive.  In fact, I found this convo by searching for whether this directive existed.  Would love to see this!

**Comment by leebyron** [comment]
Going to close this issue since the original question was answered.

We want to continue to preserve the limitation that object fields always request further fields. If you only care about existence, typically you can ask for `id` or `__typename` as a cheap way to fill this in.

**Comment by aweiker** [comment]
If you only care about the presence of something, the wouldn't better semantics be adding a _hasFoo_ field to the object?
