### ISSUE TITLE
npm: graphql@0.6.0 does not satisfy its siblings' peerDependencies

### ISSUE THREAD

**Issue by perrierism** [facebook/graphql#179]
**What is the current behavior?**

`npm install graphql express express-graphql`  

Errs : "`The package graphql@0.6.0 does not satisfy its siblings' peerDependencies requirements!`" 

**What is the expected behavior?**

Run `npm install graphql express express-graphql` (from GraphQL getting started documentation) without error

**Repro**

1. `mkdir repro;cd repro`
2. `npm init -f`
3. `npm install graphql express express-graphql`  

```
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package graphql@0.6.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer express-graphql@0.5.1 wants graphql@^0.5.0
```

**Other Info**

https://github.com/facebook/react/issues/6825 could be of interest  

The repro steps above could be good as a tiny automated test to run after each npm publish

**Comment by zpao** [comment]
This isn't related to the graphql project but the express-graphql project. This issue over there covers it: https://github.com/graphql/express-graphql/issues/89
