### ISSUE TITLE
GraphQL Clients for iOS or Android

### ISSUE THREAD

**Issue by CoericK** [facebook/graphql#180]
Hey guys, i just decided to give a try to GraphQL, and I was wondering, how can we make the requests to the graphql endpoint from an native app (android or ios) thats not build using react native (and relay). Is it possible?

**Comment by martijnwalraven** [comment]
That is definitely possible!

The easiest way would be to just make a POST request to the GraphQL endpoint with the query string in the body. That will return the query results as JSON. This approach should be enough to get you started, although it isn't the most convenient or efficient way of using GraphQL.

I'm working on more sophisticated native clients as part of the [Apollo project](http://www.apollostack.com). Among other things, it will do caching and offer a typed interface to query results. I'll be presenting about it at [React Europe](https://www.react-europe.org) next week (talks are recorded and should be online soon after).

**Comment by leebyron** [comment]
Great question and answer by Martijn.

Just to reiterate, GraphQL is a technology that is unrelated to React. Relay is an app framework that builds atop both React and GraphQL.

Not only is GraphQL usable for iOS or Android, it was built to support problems arising from mobile apps well before the Relay project started.

If you can send network requests, you can use GraphQL.
