### ISSUE TITLE
How soon will __id come to the specification?

### ISSUE THREAD

**Issue by calebmer** [facebook/graphql#188]
I heard from @josephsavona that @leebyron had a proposal to add a global `__id` field to the specification similar to Relay’s `Node` `id` field. See here: https://github.com/facebook/relay/issues/1061#issuecomment-227857031

What's the status on such a field getting added to the specification and how can we speed that process up?

**Comment by josephsavona** [comment]
The larger context is that a small number of Relay users have designed their schema such that the `id` field is a type-specific identifier (e.g. the database primary key). For a cache, however, it is substantially simpler to use global ids for object identification, and having a standardized "id" field name as part of the spec would help developers to design a schema that could be used with multiple clients (without forcing every client to deal with customizable id names).

**Comment by calebmer** [comment]
Yep, I completely understand all the benefits and as I’ve been looking into Relay alternatives a global identification spec for the entire ecosystem seems like a great idea :blush:. So I’m really excited for an `__id` specification for two reasons:

1. I am one such Relay user who has naming clashes with `id`, `__id` is an exciting solution.
2. I am a GraphQL user interested in building Relay alternatives and interesting in a “blessed” specification from the GraphQL team endorsing `__id` :blush:

**Comment by calebmer** [comment]
Last I heard here https://github.com/facebook/relay/pull/1232#issuecomment-228403233, you (@josephsavona) and @leebyron  said that an `__id` addition to the language is being considered. What are some factors under consideration and how can we make the specification definite?

**Comment by leebyron** [comment]
Yeah, we're working on this and I'll have an RFC pull request set up shortly where we can talk about it in more detail.

**Comment by calebmer** [comment]
🎉

**Comment by calebmer** [comment]
What’s the status on this @leebyron?

**Comment by Naoto-Ida** [comment]
This change would be amazing for our production GraphQL API. Can't wait to make it Relay compatible!

**Comment by leebyron** [comment]
Going to close this issue since it's a question and not a tracking RFC.

The concrete answer to the question is that __id will need to go through the RFC process, and that hasn't begun yet.

I definitely would like to address it before the April-2017 edition of the spec.

**Comment by stubailo** [comment]
@leebyron are you looking for someone to write up the `__id` RFC? I could take a pass at it.

**Comment by leebyron** [comment]
That would be great, @stubailo! Happy to collaborate on this one. We've spoken about some of the open concerns before, so perhaps you could start with the document we started a while back.

**Comment by chriscartlidge** [comment]
Hey @leebyron - we are just exploring our way into graphql and have hit into this issue which is causing us a bit of pain. 

How are we looking for a release on this? I assume the RFC still needs to be written?

**Comment by borekb** [comment]
For anyone reading this issue, the RFC PR was https://github.com/graphql/graphql-spec/pull/232.

My personal summary (please read the full discussion below the RFC yourself!) is that the `__id` field is not really a meta field in the same way that e.g. `__typename` is, for example, `__id` would be defined by users, it doesn't return a meaningful value for all types, etc. That's why it didn't get into the spec in that specific proposal.
