### ISSUE TITLE
Introspect names of fields with specific object type

### ISSUE THREAD

**Issue by aschrijver** [facebook/graphql#192]
I would like to create a single introspection query that returns the names of all fields from the `queryType` type that are of type `__TypeKind.OBJECT`

Having experimented with graphiql and read documentation and issues like #88 and #144 I get the idea this is not possible. Am I correct, or is there way to do this in plain graphql?

**Comment by IvanGoncharov** [comment]
@aschrijver Sorry for the late response.
You are absolutely correct its impossible to filter out just fields with `__TypeKind.OBJECT` types.
But you can call:
```graphql
{
  __schema {
    queryType {
      fields {
        name
        type {
          name
          kind
          ofType {
            name
            kind
            # etc.
          }
        }
      }
    }
  }
}
```
And get:
```js
{
  "data": {
    "__schema": {
      "queryType": {
        "fields": [
          {
            "name": "allFilms",
            "type": {
              "name": "FilmsConnection",
              "kind": "OBJECT",
              "ofType": null
            }
          },
          {
            "name": "film",
            "type": {
              "name": "Film",
              "kind": "OBJECT",
              "ofType": null
            }
          },
```
Than you can do your filtering with pretty simple code on the client-side.

Did I answer your question?

**Comment by aschrijver** [comment]
No problem @IvanGoncharov :)
Thank you for elightening. This answers the question well enough.
