### ISSUE TITLE
Question about "getFieldEntry" execution function

### ISSUE THREAD

**Issue by tendant** [facebook/graphql#194]
In execution section of the Spec: 

```
GetFieldEntry(objectType, object, fields):

Let {firstField} be the first entry in the ordered list {fields}. Note that {fields} is never empty, as the entry in the grouped field set would not exist if there were no fields.
Let {responseKey} be the response key of {firstField}.
```

I am a little bit confused by {responseKey} and {firstField} here: 

My understanding is:

responseKey is from field entry that is evaluating at the moment.

fields are possible list of fields when current field entry is an Object type. 

If {responseKey} is from {firstField}, how do we handle rest of fields?

**Comment by leebyron** [comment]
In this case, `fields` refers to all fields encountered with the same `responseKey`. This ensures that nested fields of the same name are both included.

Since this issue, the section has been rewritten to better clarify this case
