### ISSUE TITLE
Conditional uses of arguments

### ISSUE THREAD

**Issue by Naoto-Ida** [facebook/graphql#199]
Is there any support for conditional uses of arguments, i.e. when you have `at` and `by`,
but you can only accept an argument one at a time. Or should we write the code ourselves to check if both arguments are available in throw an `GraphQLError`?

```
GraphQLObjectType({
    name: 'Event',
    type: new GraphQLList(EventType),
    args: {
        at: {
            type: CoordinateType,
            description: 'Coordinates of the event's venue (approximate).'
        },
        by: {
            type: CoordinateType,
            description: 'Coordinates of the event's venue (exact).'
        },
    }
})

```

**Comment by IamCornholio** [comment]
Can't say I speak with authority but I think the answer is no. Your other options are to have two fields names EventAt(CoordinateType) & EventBy(CoordinateType) or an additional boolean argument to field Event(c: CoordinateType, isExact: Boolean)

Can't say I like either of those options either 😄

**Comment by Naoto-Ida** [comment]
@IamCornholio Roger that. Your option may be very close to what I need now. Thanks for the advice 😀

**Comment by sorenbs** [comment]
Cases like this is why some are arguing for union input types: https://github.com/graphql/graphql-js/issues/207 That proposal has some issues, but this is certainly an area where GraphQL could improve.

**Comment by leebyron** [comment]
Closing this aging issue. Custom code would be necessary to enforce this sort of argument usage.
