### ISSUE TITLE
Clarify cardinality in the specification

### ISSUE THREAD

**Issue by aschrijver** [facebook/graphql#201]
I find the specification opts for conciseness rather than completeness (or the information is dispersed and I can't find it).

To give an example:

> **4.2.2.2 Object**
> 
> Object types represent concrete instantiations of sets of fields. The introspection types (e.g. __Type, __Field, etc) are examples of objects.
> 
> **Fields**
> - kind must return __TypeKind.OBJECT.
> - name must return a String.
> - description may return a String or null.
> - fields: The set of fields query‐able on this type.
>   - Accepts the argument includeDeprecated which defaults to false. If true, deprecated fields are also returned.
> - interfaces: The set of interfaces that an object implements.
> - All other fields must return null.

Here `description` is okay, but what is the expected cardinality for `fields` and `interfaces` is unclear. I assume for fields it is _one-or-more_ and for interfaces _zero-or-more_.

But why not write like this:

> - fields: The set of one or more fields query-able on this type.
> - interfaces: The set of zero or more interfaces that an object implements

PS. There appears to be an IDL for the query side, but I can't seem to find it. Is there also an IDL or schema for the schema definition part of the spec. Might be nice if spec paragraphs contained a hyperlink to the relevant IDL section.

**Comment by leebyron** [comment]
This should now be handled by the "Type Validation" portions of the Type System sections. It is also inferable from the SDL grammar cardinality.
