### ISSUE TITLE
EscapedCharacter semantics seems wrong

### ISSUE THREAD

**Issue by glasser** [facebook/graphql#206]
The semantics of EscapedCharacter are defined as:

```
StringCharacter :: \ EscapedCharacter

  * Return the character value of {EscapedCharacter}.
```

I'm not sure what this actually means, but it seems to imply that you would return the same sort of thing if EscapedCharacter is `"` and if it is `n`.  Presumably this line should actually describe how b, f, n, r, and t map to other characters?

**Comment by leebyron** [comment]
Thanks for the feedback - this was fixed in the October release by adding an explicit table
