### ISSUE TITLE
Is there a conventional way to reference a particular operation?

### ISSUE THREAD

**Issue by gajus** [facebook/graphql#207]
I am writing a documentation for GraphQL service. Here is an excerpt:

> ## Authentication
> 
> Authentication is implemented using HTTP cookie.
> - Use the `mutation authenticate` operation to create an authentication session and set a HTTP cookie.
> - Use the `mutation deauthenticate` operation to destroy the associated session data and unset the authentication cookie.

Is there a prefered way to refer to a specific operation, such as I refer to the `mutation authenticate` and `mutation deauthenticate` operations in the above example?

**Comment by rmosolgo** [comment]
I don't have an answer, but I do have a clarifying question: 

Are `authenticate` and `deauthenticate` fields on your root Mutation type? 

Ie, a query might look like 

```graphql 
mutation { 
  authenticate { ... }
}
```

?

**Comment by gajus** [comment]
> Are authenticate and deauthenticate fields on your root Mutation type?

That's correct.

**Comment by rmosolgo** [comment]
I humbly suggest dot notation for referring to fields, eg `Person.name`, `Node.id`, or `Mutation.authenticate`. I think it makes sense for application-specific fields, but it's a stretch for schema entry points, what do you think?

**Comment by leebyron** [comment]
Closing this aging issue.

For a specific answer to the question, no there is not a conventional way, though I've seen both the pattern Robert described above as well as the prose "Use the `authenticate` mutation ..." used to good effect when representing top level fields.
