### ISSUE TITLE
Does GraphQL support parameter definition using input type destructuring?

### ISSUE THREAD

**Issue by gajus** [facebook/graphql#208]
I have an input type `CreateUser`.

``` graphql
input CreateUser {
  firstName: String
}
```

I am using it to define a mutation operation `createUser`.

``` graphql
type Mutation {
  createUser (user: CreateUser): User
}
```

The problem using this approach, I need to execute the `createUser` operation with a superfluous `blog` object, e.g.

``` graphql
createUser({
  user: {
    firstName: "Gajus"
  }
})
```

It would be nice if I were able to execute it using just the properties of the input type, e.g.

``` graphql
createUser(firstName: "gajus")
```

Is there a way to destructure the input type in the definition of the operation parameter? e.g.

``` graphql
type Mutation {
  createUser (...CreateUser): User
}
```

Using this declaration I am getting an error:

```
GraphQLError: Syntax Error GraphQL (45:15) Expected Name, found ...
44: type Mutation {
45:   createUser (...CreateUser): User
                  ^
```

**Comment by leebyron** [comment]
There is not a way to destructure input objects themselves. You could instead define a variable to use specifically for the `firstName`.

The reason this feature does not exist is that it would require defining an input object type for every field which accepts arguments - that would be non-intuitive and inflate the number of types in the system.
