### ISSUE TITLE
Should _all_ GraphQL scalars be present in a schema?

### ISSUE THREAD

**Issue by rmosolgo** [facebook/graphql#222]
Let's say I'm working on my BCaaS app (bean counter as a service). My only inputs are `Int`s and my only return values are `Int`s. Should my schema still contain GraphQL scalars like `String` and `Float`? Or is it appropriate to leave those types out, since they aren't used? 

It looks like graphql-js leaves out unused scalars. This approach makes sense to me. GraphQL's predefined scalars aren't "universals", instead, they're saving the user a step of defining their own. In that way, like an unused custom scalar, if a predefined scalar isn't used, it's not present in the schema.

Is that intended? Or should all GraphQL schemas contain the predefined scalar types?

**Comment by stubailo** [comment]
I wonder if GraphQL lets you override the default scalars. I would guess "no" since they are used in introspection, which should be consistent across all servers?

**Comment by leebyron** [comment]
A Schema only needs to include the scalars that are present in a schema. However note that introspection is part of the schema, and the introspection system uses String and Boolean, so those are essentially always going to appear in every schema.

**Comment by leebyron** [comment]
And @stubailo, by the spec, as long as you have a type named `String` - it must conform to the spec's description of how `String` works. So that doesn't leave much room for overriding.
