### ISSUE TITLE
how to reuse common graphql code between several graphqls ?

### ISSUE THREAD

**Issue by lizherui** [facebook/graphql#227]
For example, I have several app pages with several graphqls, which have lots of common code.

So, how can I reuse  common graphql code between several graphqls like the _#include_ in the C/C++ language or the _import_  in the Java language?

**Comment by stubailo** [comment]
You mean between different queries? That's what fragments are for!

**Comment by helfer** [comment]
@lizherui try this: http://graphql.org/learn/queries/#fragments

**Comment by leebyron** [comment]
Fragments are definitely the answer :)
