### ISSUE TITLE
Readable querying of arrays

### ISSUE THREAD

**Issue by laurenskling** [facebook/graphql#23]
If the idea is to write a query that reads as the outcome, wouldn't we want to fetch arrays differently? Right now we fetch data like this:
```
query HeroNameAndFriendsQuery {
  hero {
    id
    name
    friends {
      id
      name
    }
  }
}
```
This doesn't give me a visual indication `friends` will output an array. Why wouldn't we want to write it like:
```
query HeroNameAndFriendsQuery {
  hero {
    id
    name
    friends [
      id
      name
    ]
  }
}
```

**Comment by leebyron** [comment]
We considered this as well as another alternative:

```
query HeroNameAndFriendsQuery {
  hero {
    id
    name
    friends [{
      id
      name
    }]
  }
}
```

and decided against it as a way to simplify writing queries.

In this example, yes `friends` will return an array, but the sub fields `id` and `name` will be keys in an resulting object, so `[ id, name ]` is perhaps not quite right to describe that. 

I also found `friends [ id, name ]` confusing as I read that with the expectation that a return type would look like `{ friends: [4802170, "Lee Byron"] }` which isn't what we want either.

The hope is via well named fields (plural names), it's reasonably clear by reading a query which fields will returned as a list and which will be returned as a single value.

**Comment by leebyron** [comment]
Thanks for the critical read and feedback!
