### ISSUE TITLE
[2016 October] Section 6.4 mentions "undefined" fieldName

### ISSUE THREAD

**Issue by jlouis** [facebook/graphql#239]
In section 6.4 "Executing fields", we have the following part:

```
Let resolvedValue be ResolveFieldValue(objectType, objectValue, fieldName, argumentValues).
```

but in the same block, `fieldName` has not been defined and is not part of the arguments to the `ExecuteField` function.

(I found this because I wanted to make our code more spec-compliant, so I just started following the spec code. This is one of the gotchas I found doing this. It is rather easy to solve since you essentially have it somewhere in the scope as an escaping variable making `executeField` into a closure)

**Comment by leebyron** [comment]
Thanks for the careful read and pointing this out and so sorry this issue sat for such a long time.
