### ISSUE TITLE
Inconsistent key between query and response on __schema

### ISSUE THREAD

**Issue by chentsulin** [facebook/graphql#24]
In `IntrospectionQueryTypeQuery` section,  the query has a `queryType` key in `__schema`:
```
query IntrospectionQueryTypeQuery {
  __schema {
    queryType {
      name
    }
  }
}
```
But response with `query` key in `__schema`:
```
{
  "__schema": {
    "query": {
      "name": "Query"
    }
  }
}
```

Is there any reasons for Inconsistent keys or just a typo here?

**Comment by leebyron** [comment]
Thanks for spotting this typo!
