### ISSUE TITLE
Can a Float Value FactionalPart be empty?

### ISSUE THREAD

**Issue by dminkovsky** [facebook/graphql#242]
Over at [graphql-java](https://github.com/graphql-java/graphql-java/pull/238#issuecomment-259005359) we've run into some confusion regarding 2.9.2 (Float Value). The JS implementation lets you have an empty FractonalPart, even though it's not marked "opt" in the spec. What is correct?

**Comment by dminkovsky** [comment]
@okorz001 @pcarrier

**Comment by pcarrier** [comment]
https://github.com/graphql-java/graphql-java/pull/238

**Comment by leebyron** [comment]
Sorry for letting this issue sit.

http://facebook.github.io/graphql/October2016/#sec-Float-Value claims that a FloatValue needs either `FractionalPart` or `ExponentPart` or both, but not neither (which would be `IntValue`). 

graphql-js correctly lexes these, see the unit tests for error cases: https://github.com/graphql/graphql-js/blob/master/src/language/__tests__/lexer-test.js#L570-L582
