### ISSUE TITLE
Proposal: refactor for RxJS compatible 

### ISSUE THREAD

**Issue by xareelee** [facebook/graphql#255]
I'm starting to build another version of GraphQL library using [RxJS](https://github.com/ReactiveX/rxjs) instead of Promise for reactive programming. 

I won't add Rx to this library, just build another library and reuse most of code this library provides (with module dependency).

To minimize the efforts of maintenance, I need to refactor [this original graphql library](https://github.com/facebook/graphql) to extract Promise-associated code into separated files, and export some functions to make them importable for reuse. It won't change any behavior which this library provides. Just separate the concern of event handler (Promise, Rx, and so on) from the GraphQL design.

At a glance, I think I just need to refactor the file `graphql/execution/execute.js` mainly. The goal is make Promise-based functions become callback-based (Promise-free), and turn them into Promise-based in separated files (and also I can turn them into Rx-based easily).

**Comment by calebmer** [comment]
This should probably be opened against https://github.com/graphql/graphql-js

This repo is for the GraphQL specification which is language and implementation agnostic 😊

Let us know how it goes 👍

**Comment by xareelee** [comment]
You're right. I did not notice I posted this proposal on wrong repo.
