### ISSUE TITLE
Confusion around variables with default values and `null` value

### ISSUE THREAD

**Issue by cjoudrey** [facebook/graphql#257]
While working on an issue in `graphql-ruby`, I needed clarity on the expected behaviour of variables with default values and `null` value in the following example:

**Query**

```graphql
query ($id: ID = 4) {
  film(filmID: $id) {
    title
  }
}
```

**Variables**

```json
{
  "id": null
}
```

In `graphql-js`, `null` takes precedence over the default value of `$id` and the `film` resolver receives `filmID: null`.

The spec suggests the following algorithm for dealing with this case:

<img width="759" alt="screen shot 2017-01-05 at 5 01 15 pm" src="https://cloud.githubusercontent.com/assets/385270/21699204/a448e0cc-d368-11e6-9f67-2c93decfc40c.png">

However, I got a bit confused when I read this:

<img width="678" alt="screen shot 2017-01-05 at 5 02 23 pm" src="https://cloud.githubusercontent.com/assets/385270/21699240/bed7dc7c-d368-11e6-98ae-92c8fb2938c4.png">

It might just be me, but I got confused with "represent the lack of a value"  and "if value does not exist".

Is "represent the lack of a value" misleading?

/cc @leebyron re: #83
/cc @rmosolgo @xuorig what we were talking about

**Comment by leebyron** [comment]
I agree this can be confusing. The explicit value `null` is semantically different from no value being provided. I attempted to clear this up in #418 however please open new issues if there are still sections you find confusing!
