### ISSUE TITLE
Introspection of enum values seem to be missing

### ISSUE THREAD

**Issue by kastermester** [facebook/graphql#264]
Is there any specific reason as to why you cannot query the underlying enum value (the one the server will send for enum values as well as the one needed to send to the server when passing enum values as variables) in the introspection schema on the `__EnumValue` type, or was this just forgotten, or am I missing something obvious?

**Comment by kastermester** [comment]
Hmm having looked at this some more, it seems my initial assumption, that the value (from the graphql-js implementation) is not actually used for anything but the internal server implementation, was wrong. If this is true (that it is not used at all by the client) then I see why this is done the way it is and closing this seems like the most reasonable choice.

**Comment by stubailo** [comment]
Yep - even if you pass an Enum value via a variable, you just pass a string representing the name.

**Comment by wincent** [comment]
Thanks for bringing this up @kastermester. Going to close this as resolved but please comment again if you have anything further to add.
