### ISSUE TITLE
Input Objects Example is Invalid

### ISSUE THREAD

**Issue by schloerke** [facebook/graphql#272]
Hello,

Great document! Thank you!

I am parsing my way through the [Input Object, Input Coercion](http://facebook.github.io/graphql/#sec-Input-Objects) section.  It states input definition of 
```graphql
input ExampleInputObject {
  a: String
  b: Int!
}
```
and says an input of 
```graphql
{ 
  a: 123, 
  b: "123"
}
```
can be coerced into 
```graphql
{ 
  a: "123", 
  b: 123
}
```
.

I find this example to be impossible as the [String Input Coercion](http://facebook.github.io/graphql/#sec-String) does not allow for anything other than string inputs and the [Int Input Coercion](http://facebook.github.io/graphql/#sec-Int) does not allow for anything other than Int inputs.

This type change would make sense if it was a return value, but it is an input, which is very rigid.

Also, if the [Input Object Type Validation](http://facebook.github.io/graphql/#sec-Input-Object-type-validation) could be updated to include a comment about nullish values, that would be great.

Thank you,
Barret

**Comment by andimarek** [comment]
This PR #311 removes the wrong example.
