### ISSUE TITLE
All Variables Used Example is missing query part

### ISSUE THREAD

**Issue by schloerke** [facebook/graphql#273]
Hello,

In section [All Variables Used](http://facebook.github.io/graphql/#sec-All-Variables-Used)...

Current example:
```graphql
query variableNotUsedWithinFragment($atOtherHomes: Boolean) {
  ...isHousetrainedWithoutVariableFragment
}

fragment isHousetrainedWithoutVariableFragment on Dog {
  isHousetrained
}
```

I believe it should query on Dog first... so it should be updated to:
```graphql
query variableNotUsedWithinFragment($atOtherHomes: Boolean) {
  dog {
    ...isHousetrainedWithoutVariableFragment
  }
}

fragment isHousetrainedWithoutVariableFragment on Dog {
  isHousetrained
}
```

Thank you for all the test examples in the document! It makes my life much easier

- Barret

**Comment by leebyron** [comment]
Thanks! In the future feel free to send pull requests for things like this, which get much more visibility
