### ISSUE TITLE
Support needed for multi-line comments

### ISSUE THREAD

**Issue by thankinconcur** [facebook/graphql#276]
There's no support for multi-line comments. Something similar to Javascript support for multi-line comments would be useful (ref below).

Reference:
 https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/javascript/#multi-line-comments

Thanks!

**Comment by helfer** [comment]
@thankinconcur You can write multiline comments like so:

```
# This is a multiline comment
# in _markdown_ format about
# the user type.
type User {
  id: ID!
  name: String
}
```

It will get parsed as one comment. According to the spec you can even use markdown syntax, which GraphiQL will format nicely for you.

**Comment by thankinconcur** [comment]
Thanks Jonas; however, in the use case where there are a large number of lines to comment out, having to enter "#" on every line would not be user-friendly.

**Comment by rmosolgo** [comment]
:-1: I don't think it's worth adding complexity to the language spec. 

Considering the issue of adding `#` to every line, is that something that your editor or IDE could help with? For example, I use atom with https://github.com/bigfive/atom-sublime-select: 

![graphql-comment](https://cloud.githubusercontent.com/assets/2231765/23594790/d1508f42-01ea-11e7-9a22-796e1b03a783.gif)

**Comment by leebyron** [comment]
The exclusion of a different multi-line comment token type is intentional. I think the discussion above has helped to explain why. Simplicity is paramount and most IDEs provide great support for quickly commenting regions of text with a single command

**Comment by jedwards1211** [comment]
@leebyron except sometimes IDEs don't provide great support.  For instance Atom doesn't automatically detect that lines of a graphql query string inside a js file should be commented out with `#` instead of with `//`.

**Comment by JakubKoralewski** [comment]
@leebyron  
>  most IDEs provide great support for quickly commenting regions of text with a single command

![](https://i.imgur.com/Vyjkmk3.gif)

Provided Postman is not an IDE, but still...

**Comment by hatched-tom** [comment]
> @leebyron
> 
> > most IDEs provide great support for quickly commenting regions of text with a single command
> 
> ![](https://camo.githubusercontent.com/1dbd6aa36842e8b56451429e7efb746ebc096901/68747470733a2f2f692e696d6775722e636f6d2f56796a6b6d6b332e676966)
> 
> Provided Postman is not an IDE, but still...

if postman is on electron it's probably using codemirror or ace underneath - would be surprised if they didn't both have it as a key combo

**Comment by brainkim** [comment]
Let’s say, hypothetically, someone were to implement multiline comments in a non-standard GraphQL implementation. What do people here think it should look like? 😗

**Comment by simPod** [comment]
I tried to add rather complex comment for a field so I split it up across several lines. Then I've learnt it is not supported.

**Comment by ericscottmarquez** [comment]
ITT: lazy devs don't want to implement multi line commenting support :rofl:

**Comment by trusktr** [comment]
> @thankinconcur You can write multiline comments like so:
> 
> ```
> # This is a multiline comment
> # in _markdown_ format about
> # the user type.
> type User {
>   id: ID!
>   name: String
> }
> ```
> 
> It will get parsed as one comment. According to the spec you can even use markdown syntax, which GraphiQL will format nicely for you.

With no comments, this works:

```js
const args = `
  orderBy: {
    time: asc
  }
`

const query = gql`
  query Foo {
    someObj(${args}) {
      foo
    }

    otherObj(${args}) {
      bar
    }
  }
`
```

Add comment out a whole block in the example, and now you get a syntax error:

```js
const args = `
  orderBy: {
    time: asc
  }
`

const query = gql`
  query Foo {
    someObj {
      foo
    }

    # commented out because blah blah
    #otherObj(${args}) {
    #  bar
    #}
  }
`
```

That throws a syntax error because the actual output is this, which is very easy to overlook:

```js
const args = `
  orderBy: {
    time: asc
  }
`

const query = gql`
  query Foo {
    someObj {
      foo
    }

    # commented out because blah blah
    #otherObj(
  orderBy: {
    time: asc
  }
) {
    #  bar
    #}
  }
`
```

Multi-line comments would be extremely useful in preventing frustration with this use case.

**Comment by trusktr** [comment]
> Let’s say, hypothetically, someone were to implement multiline comments in a non-standard GraphQL implementation. What do people here think it should look like? 😗


Here's what multi-line comments could look like, avoiding the aforementioned syntax error:

```js
const args = `
  orderBy: {
    time: asc
  }
`

const query = gql`
  query Foo {
    someObj(${args}) {
      foo
    }

    #*
    commented out because blah blah
    otherObj(${args}) {
      bar
    }
    *#
  }
`
```
