### ISSUE TITLE
ID type missing in 8.2 Syntax

### ISSUE THREAD

**Issue by clentfort** [facebook/graphql#28]
While the document explicitly mentions the inbuilt type `ID` ([Section 3.1.1.1.5](From the description in [Section 3.1.1.1.5](http://facebook.github.io/graphql/#sec-Values)) it is not to be found in the the list of possible types a field can have ([Section 8.2.4](http://facebook.github.io/graphql/#sec-Values)). This leaves the `ID` type without a specific definition! Should its value be a `Name` or a `StringValue`?

**Comment by leebyron** [comment]
See "input coercion" in http://facebook.github.io/graphql/#sec-ID

> When expected as an input type, any string (such as "4") or integer (such as 4) input value should be coerced to ID as appropriate for the ID formats a given GraphQL server expects. Any other input value, including float input values (such as 4.0), must raise a query error indicating an incorrect type.

So `StringValue` or `IntValue`, but not `Name`

**Comment by leebyron** [comment]
Great feedback on this being not as clear as it could be, though
