### ISSUE TITLE
Add exact error messages to specification

### ISSUE THREAD

**Issue by neelance** [facebook/graphql#286]
The specification already defines how to return errors (e.g. query validation errors) to the client and how to specify the position of the error. I see no reason against the spec also providing the exact wording of the error messages. This would further unify the experience for GraphQL clients. They should not see any difference due to the server implementation used.

It would also make it easier to specify a GraphQL test suite which is used by multiple GraphQL server implementations to verify compatibility, see https://github.com/graphql-cats/graphql-cats/issues/5

**Comment by JeffRMoore** [comment]
A standardization around a machine-oriented error code format with possibly a handful of error codes would be better.  Then messages can evolve and not be English-centric.  Broad categories have worked well for HTTP status codes.  A good place to start would be to determine what types of actions various clients are performing based on the text of the error message (or non-standard codes).  If there is no conditional behavior client side, there isn't much need for standardization.

(Cool project, graphql-cats.  Started it to check out later.)

**Comment by neelance** [comment]
My intention was not client compatibility, but to save developer time and make the GraphQL experience more consistent. Authors of GraphQL servers shouldn't have to bikeshed about error messages. A properly defined standard would avoid that and also make acceptance tests much easier.

My current impression is that errors returned by the GraphQL error mechanism are not intended to be further processed by a machine. For example by default Relay discards all responses that have any error set. The errors are rather for telling the developer what she needs to fix to make the query work and for that they are tremendously useful. If you actually need error information for the client, then you return it as a field in your schema.

If this doesn't fit into the spec itself, then maybe it could be some kind of appendix. We could also simply use graphql-js as the authority, since it is kind of a reference implementation and I think the interactive graphiql editor uses the same messages. However, I personally would prefer a proper document.

**Comment by leebyron** [comment]
Relying on the specific error messages is not a great idea. Ideally implementations should be free to change the language of those error messages if they wish, and specifying that errors must be in English would unnecessarily push the anglo-centrism of tech even further.

Considering graphql.js is the reference impl, I think it's totally reasonable for other implementations to copy that to attempt to create consistency, but others should feel free to improve the understandability of those messages without waiting on the spec or graphql.js

I would suggest that test suites look for the existence of an error and instead look for the relevant specified error metadata (such as locations in files, or soon: error paths during execution)

**Comment by neelance** [comment]
I am using graphql.js as a reference now, no problem.

For what it is worth: English is not my first language, but I don't mind it at all. Whenever I talk to someone from a different country, I use English as the common language. This is not a tech specific thing. I think it is awesome that I can use English to communicate with most people in the world. To me, this is something that supports inclusion, not exclusion.

I am curious: Are there many non-native English speakers that see this differently?
