### ISSUE TITLE
Specification Clarification: Multiple Operations for Query/Mutations 

### ISSUE THREAD

**Issue by mhamrah** [facebook/graphql#292]
The spec states in the language section: ```When submitting a Document with multiple operations to a GraphQL service, the name of the desired operation to be executed must also be provided.``` and for Execution: ```...and a selected operation name to run if the document defines multiple operations.``` but I cannot find where the caller should specify this operation name in the request. Is it explicitly specified, or is it up to the implementation to determine the method for specifying the operation name?

**Comment by IvanGoncharov** [comment]
> is it up to the implementation to determine the method for specifying the operation name?

@mhamrah Correct.
From here: http://facebook.github.io/graphql/#sec-Executing-Requests
> To execute a request, the executor must have a parsed Document (as defined in the “Query Language” part of this spec) and a **selected operation name** to run if the document defines multiple operations, 

There is also a recommendation on how it should be implemented over HTTP:
http://graphql.org/learn/serving-over-http/#post-request

**Comment by wincent** [comment]
Thanks for answering, @IvanGoncharov. If you still have any questions, @mhamrah, please feel free to comment again.
