### ISSUE TITLE
Possibility of collaboration with LoopBack framework?

### ISSUE THREAD

**Issue by raymondfeng** [facebook/graphql#3]
I'm a developer of LoopBack (http://www.loopback.io), an open source Node.js framework for building APIs with rich data integrations. I'm opening this issue to explore the possibility of collaboration as both projects try to solve similar problems. 

LoopBack already provides a lot of capabilities as you outline in the GraphQL spec, including:

1. A JSON based definition language for data models (types and validations) - http://docs.strongloop.com/display/LB/Model+definition+JSON+file
2. Relations that connect models (BelongsTo, HasMany, HasOne, HasMany-Through, EmbedsMany, ReferencesMany, Polymorphic) to form data graphs - http://docs.strongloop.com/display/LB/Creating+model+relations
3. A JSON based query language - http://docs.strongloop.com/display/LB/Querying+data
4. A large list of connectors that implement the CRUD operations based on the specs - http://docs.strongloop.com/display/LB/Connecting+models+to+data+sources

What do you think? 

PS: I'm not sure if this is a good way to reach out. Please let me know if we should take it offline. Thanks in advance.

**Comment by leebyron** [comment]
This is interesting, feel free to drop me an email to talk more in depth. I'm curious to know what you imagine a collaboration looking like in this case.

**Comment by leebyron** [comment]
Closing this. Looking forward to following up over email

**Comment by sebastienbarre** [comment]
I would certainly be interested to know if anything came out of this exchange.

I just read [Start using GraphQL with Graffiti](https://blog.risingstack.com/start-using-graphql-with-graffiti/): "Graffiti provides an express middleware, a hapi plugin and a koa middleware to convert your existing models into a GraphQL schema and exposes it over HTTP."

This made me wonder if, similarly, a REST API designed with Loopback could also be automagically exposed as a GraphQL endpoint... (I'm evaluating both hapi vs. loopback at this point).

**Comment by altsang** [comment]
hi @leebyron and @sebastienbarre, sorry for the late reply, I'm back from my vacation.

coincidentally, we're actually in the process of kickstarting a React SDK with another community member - @LucaColonnello.  I can make some introductions via email.  @leebyron I have your thread from @raymondfeng .  @sebastienbarre if your'e interested please ping me at `al (at) strongloop.com`.  
@LucaColonnello has put together a set of options in a proposal that you guys can review.

Here at SL, we're going take isomorphic LB in the browser, strip it down to be more lightweight so that a React based MVC like Flux can bind to the JS objects directly to implement objects like Store.

**Comment by LucaColonnello** [comment]
Yeah guys,
integrate GraphQL and Relay with Loopback (with the in browser implementation) could be great!

Now I'm working on a demo made in React as a porting of the Angular once of the ToDo example.

**Comment by altsang** [comment]
@LucaColonnello - do you mind posting the Gist and the slides so folks can get on the same page? thx!

**Comment by LucaColonnello** [comment]
Oh Yeah,
these were only Draft, but I think that working together we can create something really cool!!!!!!!!!!


Example gist:
https://gist.github.com/LucaColonnello/55ffd0a311bbf64becc1

Slides.com presentation of some ideas:
http://slides.com/lucacolonnello/react-sdk-for-loopback/#/

**Comment by altsang** [comment]
:+1:

**Comment by equinusocio** [comment]
:+1:

**Comment by esco** [comment]
:+1:

**Comment by SharpEdgeMarshall** [comment]
:+1:

**Comment by equinusocio** [comment]
:8ball:

**Comment by ilianaza** [comment]
:+1:

**Comment by christianpv** [comment]
:+1:

**Comment by beeman** [comment]
:+1:

**Comment by gausie** [comment]
:-1:

**Comment by gausie** [comment]
wait I mean :+1:

**Comment by proteamer** [comment]
:+1:

**Comment by leebyron** [comment]
Closing this thread since this discussion should be driven from loopback and there's no action to be taken from this repo.

**Comment by leebyron** [comment]
See https://github.com/strongloop/loopback/issues/1841
