### ISSUE TITLE
__Field args should not be required

### ISSUE THREAD

**Issue by schloerke** [facebook/graphql#302]
`__Field` is currently defined as:

```graphql
type __Field {
  name: String!
  description: String
  args: [__InputValue!]!
  type: __Type!
  isDeprecated: Boolean!
  deprecationReason: String
}
```

This definition states that arguments are required for all fields.  I believe it should be defined as `args: [__InputValue!]`, where the args value may be nullable, but if there are any elements, they must be NonNull elements.

Thank you,
Barret

**Comment by IvanGoncharov** [comment]
> This definition states that arguments are required for all fields.

@schloerke No, `args` can be an empty array. 
It's better to have only one way to represent the absence of args on a field so I'm against this change.

**Comment by schloerke** [comment]
@IvanGoncharov 
Correct!  I forgot about a length 0 array being ok. (It doesn't contain any null elements.)

Sorry for the troubles! Thank you

**Comment by wincent** [comment]
Thanks for raising the issue @schloerke, and @IvanGoncharov for chiming in and helping clear things up!
