### ISSUE TITLE
unclear language in specification about ordering

### ISSUE THREAD

**Issue by grahamegrieve** [facebook/graphql#309]
the specification says "Serialization formats which can only represent unordered maps should retain this order grammatically (such as JSON)."

I know standards and JSON ok, but I have no idea what that is trying to say. Clarification would be in order

**Comment by wincent** [comment]
Is this clearer?

> Serialization formats such as JSON which can only represent unordered maps should still retain the ordering textually. That is, if two fields `foo` and `bar` were queried in that order, the resulting JSON serialization should contain `"foo": "...", "bar": "..."`.
