### ISSUE TITLE
post request query with parameter does not work, but works in graphiql

### ISSUE THREAD

**Issue by benjaminhon** [facebook/graphql#313]
the following query on my graphql server works using graphiql
```
query {
  map(id: "actlab") {
    id
  }
}
```

however when doing a request from a http post, it returns nothing, no map was found with id = actlab

```
request = ({query, variables}) ->
  axios({
    method:   'post'
    url:      "#{graphqlUrl}"
    headers:  {'Content-Type': 'application/json'}
    data:     JSON.stringify({query, variables})
  })

variables = {id}
query = "
  query ($id: String!) {
    map (id: $id) {
      id
    }
  }
"
request({query, variables})
```
it seems that there is a problem with the variables passing over can anyone help? thanks

**Comment by stubailo** [comment]
I don't think this repository is the right place for the issue, since this is about the specification which doesn't talk about HTTP. You might want to open it on whatever GraphQL server implementation you are using.

**Comment by esseswann** [comment]
I agree with @stubailo. Anyways in most implementations you do not stringify `variables` , and send them under a corresponding key in a JSON request
