### ISSUE TITLE
Clarification on Lists of Non-Null objects

### ISSUE THREAD

**Issue by TOTBWF** [facebook/graphql#316]
If I have a list of non nullable objects `[Obj!]`, and one of them ends up resolving to null, do you silently remove the offending element from the list and throw an error, or does the entire list resolve to null? The wording on the spec deals with fields of objects, but not lists.

**Comment by calebmer** [comment]
The entire list resolves to null. If you only want a single item to resolve to null then declare the type as `[Obj]` 😊

**Comment by TOTBWF** [comment]
Thanks 🙂 This should probably be mentioned in the spec somewhere, would anyone object to a PR adding it?

**Comment by calebmer** [comment]
I doubt it 😊
