### ISSUE TITLE
Basic authentication

### ISSUE THREAD

**Issue by vincentpageau** [facebook/graphql#333]
I'm receiving this error when trying to query my graphQL API that uses **Basic authentication**:
`Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.`

My code to create my networkInterface is:

```
networkInterface = createNetworkInterface({
    uri: graphQlEndpoint.uri,
    opts: {
      credentials: graphQlEndpoint.credentials
    }
  });

  networkInterface.use([{
    applyMiddleware(req, next) {
      if (!req.options.header) {
        req.options.headers = {};
      }
      req.options.headers.authorization = 'Basic authorizationCode';
      next();
  }
}])
```

I'm guessing the problem here is that before my webapp makes the query, it sends a preflight request and that's where I receive the **error 401**. I was wondering if that was really the reason why I get an error there.

If so, is there a way to fix it?

Is there another authentication thats works better than Basic authentication in this situation?

*note*: I'm using **node.js**, **react**, **apollo-client**

Thank you for any help you can give me.

**Comment by TOTBWF** [comment]
This repo is for discussing the formal GraphQL specification, I would head to the graphql slack, they tend to be pretty knowledgeable.

**Comment by vincentpageau** [comment]
Ok my bad there.
Thanks for the heads up !
