### ISSUE TITLE
Subscriptions not found in official documentation

### ISSUE THREAD

**Issue by kingisaac95** [facebook/graphql#334]
I was writing an article on GraphQL subscriptions and wanted to point to the official documentation on graphql.org/learn/ but I noticed that the word "subscription" does not appear anywhere in the document.
So I thought I should raise this here.
Can I write a little documentation on it that could be added to the documentation? I know you guys are really doing a great job in making GraphQL more efficient and I want to contribute in any way I can.

**Comment by TOTBWF** [comment]
For a detailed information on Subscriptions, look at the spec, specifically section [6.2.3](https://facebook.github.io/graphql/#sec-Subscription).

**Comment by kingisaac95** [comment]
Thanks @TOTBWF

**Comment by stubailo** [comment]
@kingisaac95 here would be the place to add that! https://github.com/graphql/graphql.github.io/

I'm happy to review that, I wrote the original queries and mutations content :]

**Comment by kingisaac95** [comment]
Thanks @stubailo. I'll reach out once I done with it.

**Comment by rokob** [comment]
@TOTBWF That link doesn't work anymore, any reason subscriptions are no longer in the published spec?

**Comment by IvanGoncharov** [comment]
@rokob http://facebook.github.io/graphql/  now points to lastest official release (see #364) which is predates subscriptions. You can see latest draft here: http://facebook.github.io/graphql/draft/ and it includes subscriptions.

P.S. I also was surprised until I checked [publish.sh](https://github.com/facebook/graphql/blob/master/publish.sh).

**Comment by jmeas** [comment]
I thought this was odd, too. Luckily I found this issue! I opened a PR over in #473 to update the website for the time being.

**Comment by leebyron** [comment]
Closing in favor of https://github.com/graphql/graphql.github.io/issues/584
