### ISSUE TITLE
Clarify how to merge fields in field selection

### ISSUE THREAD

**Issue by Peping** [facebook/graphql#347]
Currently the GraphQL spec at https://facebook.github.io/graphql/#sec-Field-Selection-Merging only mention conditions that have to apply in order for fields in a selection to merge. While discussing a fix to an issue ( Youshido/GraphQL#138 ) the specification was brought up.

It is pretty confusing to infer how to actually merge fields in a selection just from the specs alone, because they only seem to be talking about how to know when multiple fields can merge, and not about how to actually do the merging.

Can we get some more specific documentation on how to merge fields? Can we get some examples of how to merge fields of object types and array types?

**Comment by leebyron** [comment]
What you've linked to there is the validation rule that ensures merging fields is safe, the actual work is done in:

http://facebook.github.io/graphql/draft/#CollectFields()

I'll add a reference from the validation rule so as you're reading you find that back-reference
