### ISSUE TITLE
Upload a file(image)

### ISSUE THREAD

**Issue by raderio** [facebook/graphql#349]
Is it possible to upload a file using GraphQL?

**Comment by robzhu** [comment]
It's not a common use-case for GraphQL, but yes: https://medium.com/@danielbuechele/file-uploads-with-graphql-and-apollo-5502bbf3941e

**Comment by chintan-mishra** [comment]
Is it on the roadmap to include the functionality to upload images, BLOBs, videos, files, etc.?

**Comment by raderio** [comment]
Why is this issue closed?
