### ISSUE TITLE
[Documentation] Official GraphQL documentation Chinese translation contributing request

### ISSUE THREAD

**Issue by wenqingyu** [facebook/graphql#350]
### Documentation contribution request

We are a China's tech team ([NightPlus](http://nightplus.sxl.cn/)) who heavily using GraphQL as primary external API standard. We allied some other talented tech companies here in China to translate GraphQL documentation pages into Chinese as a team, that way more Chinese developers will have opportunity to get involved GraphQL. 

We folked graphql.github.io and followed code standard and translate all content into Chinese, this project is about finished finalized soon, and **we are wondering if we can PR this version into major branch as Chinese version of official site.** This will give our passionate developers a great cheer.

We've got some professional translators in this translating team to help us collated syntax and interpretation consistency, they are experienced in translating plenty of technology and coding tool books, **so after several rounds of check, we believe it is qualified to present as official document in Chinese.**

This is our folk repo [https://github.com/xitu/graphql.github.io](https://github.com/xitu/graphql.github.io)

We believe this translation task will be valuable effort to grow a stronger GraphQL community here in China. And we are trying to contribute more to tech community to gain good reputation and bring more talented, passionate developers join us. **It will be awesome if GraphQL official site could give some credits to our tech team and translation partner.** Maybe give these contributor companies logo a chance to expose on official website, or any other way convenient. 

**Anything please feel free to contact wenqing@nightplus.cn.**

**Major Contributor partner**
[juejin.im](https://juejin.im/)
[NightPlus](http://nightplus.sxl.cn/)

**individual contributors not included**

**Comment by leebyron** [comment]
It would be great if you could please move this effort to the https://github.com/graphql/graphql.github.io/ repository! Translated docs would be highly valuable there.
