### ISSUE TITLE
Best type to use for >32-bit integers should be documented

### ISSUE THREAD

**Issue by nakedible-p** [facebook/graphql#366]
Public APIs often contain fields whose values are naturally integers, but which exceed 32 bits. For example:

- `fileSizeBytes`
- `millisecondsSinceEpoch`
- `secondsSinceEpoch` (values after 2038)
- `freeMemoryBytes`
- `monetaryAmount` (in ISO 4217 meaning integer and fixed exponent)
- `databaseRowId`
- `youtubeViewCount`
- `facebookActiveUsersCount`
- `uniquePageVisitorCount`

These numbers are sometimes larger than 32 bits, but almost universally smaller than 53 bits. These numbers are also almost everywhere, and most users will have to figure out how to represent them - or how to work around the problem instead. A real world example is GitHub GraphQL API, where repository `diskUsage` is given in kilobytes instead of bytes, and with the `Int` datatype, meaning that the API needs to be changed when the first repository larger than 2 terabytes appears.

So, what is the recommended universal default way to represent such numbers in GraphQL:

- `Float` (which works, but does not convey that the number is an integer, so requires additional validation)
- Custom `Int53` type (works, but not in standard)
- Custom `Int64` type (works, but not in standard, also would map to BigNum in JavaScript unnecessarily)
- `String` (requires conversion client side and server side, additional error handling)

Because these cases are so common, I would like to get a definitive answer on what is the default way to handle them, and I would also hope this would be added (as an informative note) to the documentation, so people would actually know about it.

Or alternatively, the best solution in my opinion: update the specification to actually contain an integer datatype >32 bits, since it is still a working draft instead of a standard. But, it may be way too late for that, I don't know.

I am willing to do the legwork for any such change, but without a decision I don't think there's much I can do about this.

**Comment by nakedible-p** [comment]
@leebyron @wincent Sorry to bother, but this issue has just sat here for a month. How and where should I open a discussion about this? What is the proper place for graphql spec feedback?

**Comment by wincent** [comment]
> What is the proper place for graphql spec feedback?

The issue tracker here is a reasonable place to start. If you want to go beyond an initial exploratory conversation about a topic then see [CONTRIBUTING.md](https://github.com/facebook/graphql/blob/master/CONTRIBUTING.md) in the root of the repo for a description of the basic stages that a proposal to change the spec should generally go through (the process itself is evolving, but that document captures some current thinking about it).

> I would like to get a definitive answer on what is the default way to handle them

That is going to be tricky as there may not be a "definitive" answer as such. The 32-bit int size was very intentionally chosen for maximum interoperability, knowing that pretty much all significant, current systems that one might wish to use GraphQL with will be capable of representing numbers in this way. Once you want to go beyond that, you are pretty much inevitable in the territory of the implementation-specific, which means that it is going to be difficult to get it into the spec. Even if just in a supplemental, advisory addendum; part of the value of the spec is that it can reasonably be implemented in its totality *everywhere*, and once you start adding additional layers of guidelines it is no longer necessarily clear where the "core" spec ends and the "optional" part begins. What does it means to say a library "implements the spec"? I could go on, but you can probably see where the logical conclusions lie.

**Comment by jlouis** [comment]
I wonder if a document in the spirit of the `Relay Modern Conventions` could be beneficial. GraphQL doesn't define eg pagination, but in `Relay Modern` there is a convention for doing just that on top of GraphQL. It might be useful to have a document which defines an "extended type Zoo of commonly used types" which a server can adhere to.

Some of the trickery that is going on here is that different languages treat integer values differently:

* Erlang, Common Lisp, and Haskell defines arbitrarily sized integers by default. Hence, they have no problem dumping you a 160bit integer as a result.
* OCaml uses one bit for tagging in its integer scheme. Thus integers are 63 bit by default and the 64 bit integers have a considerable performance degradation if you use them.
* Perl, and Javascript doesn't define an integer type at all and are thus only precise up to 53bit
* SQL has a DECIMAL type for fixed point arithmetic.

If a spec tries to cater to a specific language, you exclude some languages from the implementation. So it makes sense to start with a lowest common denominator. Other considerations:

* JSON might not be the transport. Other transports define different integer types. Expect coercions.
* Were I to define some of the above types, I'd probably define them as user-defined scalar types and build proper resolvers in the languages I intend to work with. Poly-language systems tend to need some special handling when traversing the language barrier anyway.

**Comment by leebyron** [comment]
I'm going to close this issue since I think it's been thoroughly discussed. To conclude:

> So, what is the recommended universal default way to represent such numbers in GraphQL?

There is no recommended universal default. Different APIs will come to different conclusions based on the type of data they need to represent and the kinds of clients they expect to support. All of the options you offered are reasonable to consider when making this choice. `Float` may be best if you can guarantee < 52bit ints and expect clients to do math on them. `String` may be best if you aren't sure about precision but only expect clients to print the number anyhow. A custom scalar type may be best if you need to encode rules for a specific transport (Protobuf?) or client paring (BigInt?)

**Comment by nakedible-p** [comment]
I'm going to respect the decision to leave this out of the spec. However, for posterity, I will express my disagreement with the issue here.

I fear that not recommending an universal default does not result in people choosing the best type based on the type of data. I fear that they will instead stick with 32-bit integers, hoping that they will be enough, until they are not. Github using integer for repository size is already an example of this - it will break with the first 2 terabyte repository. I am betting that if YouTube adds a GraphQL API for their service, the person implementing that will decide that `viewCount` property for a video should be of type `Int`, because it is the most natural type for such a value, completely forgetting that YouTube has almost 20 videos with more than 2 billion views. When the general migration from 32-bit OS to 64-bit OS happened, we saw this sort of thing en masse, and it was a very painful transition - and currently the integer size is no longer an issue as the *default* selected integer in programming languages can be larger than 32-bit. It feels like a renaissaince back to those days, getting all these 32-bit problems again.

But even when people select a datatype larger than 32-bits for the GraphQL API, the end result is not going to be terribly nice since everyone will select differently. This means conversions between the different types across the board. This is similar to Java, where half of the APIs decide they want `long` and half of them want `int`. The result is typecasts all around, warnings about possible loss of precision, and hard to diagnose bugs because people don't want to use conversion helpers that will error out if the value exceeds the new range.

The only solution to both of these problems is that the *default* type people pick for an integer is large enough for most uses. If this default integer type would be 53-bit integer, it would be represented by the following types in programming languages:

| Language | Type |
| --- | --- |
| JavaScript | Number |
| Python | int (or automatically long for 32-bit Python 2) |
| C/C++ | int64_t |
| Go | int64 |
| C# | long |
| Java | long |
| PHP | integer (or automatically float for 32-bit) |
| VB.NET | Long |
| OCaml | int (or, unfortunately Int64 for 32-bit, but see below) |

Note: OCaml has 31-bit integers on 32-bit platforms, so even the current GraphQL default for "maximum" compatibility cannot be represented by them, forcing the use of Int64 for 32-bit platforms. So this does not 

I don't know, maybe my viewpoint is limited, but I fail to see in what kind of environments this would actually pose a problem. Sure, some embedded controllers for IoT are mostly 32-bit, and might have slow 64-bit numbers, and might access GraphQL APIs - but I doubt the integer size problem would be a major obstacle there.

**Comment by nakedible** [comment]
In case somebody stumbles upon this from a search, I created a custom scalar for this and published the library: https://github.com/nakedible/graphql-scalar-int53

**Comment by acjay** [comment]
In the spirit established in Relay of making specs outside of the GraphQL spec for auxiliary ideas, maybe that's what's needed here, so that libraries can adopt a uniform approach.
