### ISSUE TITLE
Writing a hierarchies of objects using GraphQL

### ISSUE THREAD

**Issue by davidonlaptop** [facebook/graphql#374]
Assuming I have a hierarchy of records: `Team`, `Player`, `Address`, `Telephone` with the following relationships:
- A `Team` has many `Players`
- A `Player` has many `Addresses`
- A `Player` has many `Telephones`

Is it possible to write a mutation that sends all the data in one call ?

From the [docs](http://graphql.org/graphql-js/mutations-and-input-types/):
> Input types can't have fields that are other objects, only basic scalar types, list types, and other input types.

Is there a workaround?

**Comment by IvanGoncharov** [comment]
@davidonlaptop Input types support other input types as fields, so you can write:
```graphql
type Mutation {
  addTeam(data: TeamData!): Team
}
input TeamData {
  players: [PlayerData!]
}
input PlayerData {
  addresses: [AddressData!]
  telephones: [TelephoneData!]
}
```

**Comment by davidonlaptop** [comment]
Perfect! Thanks Ivan

**Comment by jlouis** [comment]
Let me add that my experience is that it is very useful to have a stratified world of *input* objects and *output* objects. Often, your `TelephoneData`, `AddressData` and like objects have vastly different structures than their corresponding output types. Hence, keeping them as separate types means that a client cannot mess them up by accident.

To see why they are different, one can start with a simple observation: something like `AddressData` is unlikely to have an `id` field and hence they don't have *identity*. They get identity once they are inserted however. Another example is that the input might invoke some kind of address parser on a `string` and then split it into appropriate fields as well.

While you design your schema, it is also worth pondering if your inputs are *product types* (i.e., objects) or if they are *scalar* types. If the telephone should only ever work in one country, you may regard it as a scalar, or you could define the representation as a string "+1 ...." for the CC. An alternative representation is as an object consisting of fields `countryCode, areaCode, ...`.

Finally, an important rule is that *interfaces* and *unions* are "output types" (in type-checking-speak you could say that they have *negative mode* or *negative polarity*). And hence they are not allowed as inputs in GraphQL. You will have to be explicit when you enter data as inputs in a query.

**Comment by davidonlaptop** [comment]
> Finally, an important rule is that interfaces and unions are "output types" (in type-checking-speak you could say that they have negative mode or negative polarity). And hence they are not allowed as inputs in GraphQL. You will have to be explicit when you enter data as inputs in a query.

Interesting... It would be nice if input types could inherit from other input types.
