### ISSUE TITLE
Proposal: Type Versioning

### ISSUE THREAD

**Issue by iamclaytonray** [facebook/graphql#380]
I've recently run into a use-case where versioning specific resources would be incredibly helpful with my GraphQL API. I have probably only spent ~2 months with GraphQL so I potentially could have missed something where this is concerned. Anyway, let's take the following example and go from there:

---

**Post 1.0**

"I went to the beach today."

**Post 1.1**

"I went to the beach today **and I got really sunburned.**"

---

Currently, achieving something similar to this is really involved and no solution feels right. It more-or-less just feels like I'm hacking together a temporary solution. I think the use-case for adding versioning capabilities to the spec would eliminate both confusion and complexity. 

I know that GraphQL is versionless but from my understanding, that is both intentional and for the API as a whole. Would something to this extent even be possible? Do you think that this use-case is actually helpful to others? I'm open to discussing this in greater detail. (If something like this exists, can you point me to the right direction? All of my search queries have returned everything about GraphQL as a whole being versionless. I couldn't find anything for my use case.)

**Comment by iamclaytonray** [comment]
Here's an implementation of how I think this would look. Also, I may have gotten something wrong here but you get the idea.

```graphql
type Post {
  id: ID!
  title: String!
  body: String!
  version: Version! # Version if this becomes an official Type in the spec,
  # otherwise, would "version" just be an Int or Float, with some background magic/logic?
}

query Post($id: id, $version: version) {
  Post(id: $id, filter: { version: $version }) {
    id
    title
    body
  }
}
```

**Comment by iamclaytonray** [comment]
It seems as if these issues are not looked at too often... Is there a better place to hold discussions?

**Comment by omRm** [comment]
This is the right place, it just takes a bit of time.

Something like these would be easily implemented into your Object, rather than a new Versioning Type.
Why not just put your Post type in an Array ?

**Comment by iamclaytonray** [comment]
I'm unaware of the ability to put a Type into an array. But even if it were possible, that opens the door for a lot of problems. The first I can think of is querying a single Post. I'm not sure how well it would work with Mutations either. I think this feature is completely valid

**Comment by omRm** [comment]
I too think this is worth a discussion.

Why not put a list of postHistorys in your Post ?

```graphql
type Post {
  id: ID!
  title: String!
  postHistory: [PostHistory!]
}
```
and then just query with a Version? see here: https://launchpad.graphql.com/n7nl337n7
mutations will be a bit tricky, and there are surely even better ways to do this.
It just feels like versioning history some chunk of business logic that graphql does not need to support the way you described

**Comment by iamclaytonray** [comment]
Out of the box, that wouldn't work. I'd have to write a bit of logic to implement that. However, if it were part of the spec, this feature could be written in existing implementations. (Both by the community and by graphql/graphql-js).

The only problem that I foresee in an implementation of this is the various databases that you would need to go through to correctly grab those previous versions. I'm really not sure how the implementation details would look. I've been pondering this since I wrote this issue.

**Comment by rmosolgo** [comment]
> if it were part of the spec, this feature could be written in existing implementations

You wouldn't want us _implementors_ to take all the fun now, would you? 😉 

For real though, the most successful new features have followed the _reverse_ process. Instead of going into the spec first, then into a real-world application, they _start_ in an application and then become part of the spec. (Subscriptions stand out -- FB built subscriptions _on top_ of the spec first, then opened an RFC to update the spec.)

So, if you think this idea is valuable, how about demonstrating its value first, and showing how it may be implemented? With a good demonstration, more of us may be convinced that it's a good addition to GraphQL at the language/runtime level.

**Comment by iamclaytonray** [comment]
That sounds like a good plan. I'll go ahead and fork graphql-js to get started. Thanks for the advice 😄

**Comment by leebyron** [comment]
I'm going to close this issue since it sounds like you got answers, @iamclaytonray 

The example query you wrote at the top of this issue is very much fulfillable today. I don't see any missing features to fulfill such a use case that the spec does not provide for. The `Version` type you propose could easily be a custom scalar type, or more often I've seen versions for resources like this be represented as incrementing `Int` values.

**Comment by iamclaytonray** [comment]
@leebyron - I don't think that incrementing `Int` values would return a previous `Post`, for example. The idea isn't to return a Version number, but rather be able to access a sequence of previous `Post`s (or any other type of resource) and all of it's data. I'm still pretty new to GraphQL but I don't see where adding a Scalar type would help in this use-case. This isn't really a question. It's more of a "I will submit a PR if this is something that would be potentially accepted"
