### ISSUE TITLE
Proposal: "Preparing" arguments

### ISSUE THREAD

**Issue by nijynot** [facebook/graphql#387]
The idea is similar to how you can prepare variables in relay before using them.
So, the proposal is to add a layer before using the arguments in the resolve field.

Example in javascript:
```
export const userMutation = {
  type: userType,
  args: {
    id: {
      type: GraphQLID,
      prepare: (arg) => {
        return arg + 1;
      },
    },
  },
  resolve: (obj, args) => {
    // here args.id is incremented by 1
  },
};
```
This could be useful when IDs are in base64, so that it's easier to use e.g. `fromGlobalId` with relay.

Another use case is for pagination. So I set up a basic "connection type" with `limit` and `offset` argument. Then to see if there's a next page, I query for `limit + 1` in my db. Instead of incrementing in my resolve, it would be much easier to do this:
```
args: {
  limit: {
    type: GraphQLInt,
    prepare: (arg) => {
      return arg + 1;
    },
  },
},
resolve: (obj, args) => {
  // args.limit is incremented by 1
}
```
as I reuse the connection type.
Though, maybe I'm just missing something or just using GraphQL wrong?
Would love to know if someone else has this issue.

Edit: Btw, am I posting this in the wrong repo? Maybe this should be in the graphql-js repo rather than this one?

**Comment by leebyron** [comment]
This feels like an implementation detail, and not something that would affect the GraphQL specification. I'm going to close this issue, but feel free to open issues on repos for GraphQL server implementations to further the conversation.

Though to give early feedback, I'm not sure I see the value offsetting the complexity cost. 

```
args: {
  limit: {
    type: GraphQLInt,
    prepare: (arg) => {
      return arg + 1;
    },
  },
},
resolve: (obj, args) => {
  // args.limit is incremented by 1
}
```

Seems like strictly more and more complicated code than

```
args: {
  limit: {type: GraphQLInt},
},
resolve: (obj, args) => {
  const limit = args.limit + 1;
}
```
