### ISSUE TITLE
[RFC] Typed error

### ISSUE THREAD

**Issue by oney** [facebook/graphql#391]
For now, GraphQL lets developers decide errors' format, which makes developer bewildered.
For example,
```graphql
type Mutation {
  register(input: RegisterInput!): User!
  verifyPhone(pin: String!): Phone!
}
```
`register` may have errors like email format is wrong, email already used, password is too easy. So its error is like
```json
{
  "errors": [
    {
      "message": "Email not found",
      "fields": [
        { "field": "Email", "message": "Email format is wrong" },
        { "field": "Password", "message": "Password is too easy" },
      ]
    }
  ]
}
```
`verifyPhone` may have two types of error
```json
{
  "errors": [
    { "message": "Pin is wrong", "type": "wrong" }
  ]
}
```
or 
```json
{
  "errors": [
    { "message": "Pin is expired", "type": "expired" }
  ]
}
```
These errors are so different, so I can't just use the same formatting implementation of `formatError`.

One way to solve it is
```graphql
type RegisterValidateError {
  message: String
  fields: [ValidationField]
}
type RegisterPayload {
  user: User
  error: RegisterValidateError
}
enum VerifyPhoneErrorType {
  wrong
  expired
}
type VerifyPhoneError {
  message: String
  type: VerifyPhoneErrorType
}
type VerifyPhonePayload {
  phone: Phone
  error: VerifyPhoneError
}
type Mutation {
  register(input: RegisterInput!): RegisterPayload!
  verifyPhone(pin: String!): VerifyPhonePayload!
}
```

But I think it'll be good if GraphQL supports native typed errors and add `throws` keyword to hint clients which errors might throw in the query.
So it'll be like the following
```graphql
error RegisterValidateError {
  message: String
  fields: [ValidationField]
}
enum VerifyPhoneErrorType {
  wrong
  expired
}
error VerifyPhoneError {
  message: String
  type: VerifyPhoneErrorType
}

type Mutation {
  register(input: RegisterInput!): User! throws RegisterValidateError, RegisterTooManyTimesError
  verifyPhone(pin: String!): Phone! throws VerifyPhoneError
}
```
And the response's errors have the type
```json
{
  "errors": [
    {
      "type": "RegisterValidateError",
      "message": "Email not found",
      "fields": [ ... ]
    }
  ]
}
```

**Comment by timsuchanek** [comment]
Is there any update here?

**Comment by leebyron** [comment]
This seems like a misuse of errors to me. GraphQL errors encode exceptional scenarios - like a service being down or some other internal failure. Errors which are part of the API domain should be captured within that domain.

Of the two suggestions you make here, I strongly prefer the first one. It is much simpler, the behavior is clear to any reader, and it requires no new changes to GraphQL. However the second accomplishes the same task but requires new syntax and behavior and is less clear how "fields" on errors would be selected.
