### ISSUE TITLE
[RFC] Add Class

### ISSUE THREAD

**Issue by oney** [facebook/graphql#393]
GraphQL is very powerful for query, but is weak for mutation in my opinion. Second, GraphQL is based on resolvers, there is no resources concept which makes create, update and destroy actions complex.

For example, there is `User` type, we can CRUD it like RESETful API
```graphql
query {
  allUsers: [User]
  user(id: ID): User
}

mutation {
  createUser(input: UserInput): User
  updateUser(id: ID, input: UserInput): User
  destroyUser(id: ID): User
}
```
If we have 5 or more types like `User`, GraphQL schema will become hard to manage.

My proposal is add `class`, things will like
```graphql
class User {
  init(id: ID)
  mutate init(params: User.Lets)
  static all: [User]
  var name: String
  let username: String
  followingCount: Int
  createdAt: Date
  mutate update!(params: User.Vars): Boolean
  mutate destroy(): Boolean
  mutate follow(userID: ID): Boolean
  articles(state: ArticleState): [Article]
}
```
And you can use it like
```graphql
query($createParams: User.Lets, $userID: ID, $updateParams: User.Vars, $followUserID: ID) {
  User.all { # Get list
    id
    name
  }
  User(params: $createParams) { # Create
    id
    name
  }
  User(id: $userID) {  # Read
    update!(params: $updateParams) # Update
    name
    username
    follow(userID: $followUserID)
    followingCount
  }
  User(id: $userID) {
    destroy # Destroy
  }
}
```

Field types are
* `var`: e.g. `var name: String`
* `let`: e.g. `let username: String`
* `default`: e.g. `followCount: Int`
* `mutate`: e.g. `mutate update!(params: User.Vars)`

For `var` and `let`, it will automatically generate inputs `User.Vars` and `User.Lets`.
```graphql
input User.Vars {
  name: String
}
input User.Lets {
  name: String
  username: String
}
```
`User.Vars` only includes `var` fields and `User.Lets` includes `var` and `let` fields.

For `mutate`, it means the query is a mutation.
For `default`, it just normal fields.

The reason we have `var` and `let` is that `let` fields should only be used on creating and `var` can be used on creating and updating.

Let's take a closer look at
```graphql
  User(id: $userID) {
    update!(params: $updateParams)
    name
    username
    follow(userID: $followUserID)
    followingCount
  }
```
This query has two mutations `update` and `follow`. Although `follow` is below `username`, GraphQL will still execute all mutations serially first and then resolve other fields e.g `name`, `username` and `followingCount` parallelly.

What does `!` mean?
It means the resolvers will return both parent and result, and returning parent will replace the original one.
```js
const userType = {
  update: (parent, args, ctx) => {
    // ...
    return { parent: obj, result: result }
  }
}
```

**Comment by leebyron** [comment]
Sorry for letting this sit, I'm closing aging issues.

I'm not sure this proposal will gain much traction because it seems to be introducing a lot of new ideas and concepts for which there are existing concepts. In general GraphQL services philosophically avoid the Mutative-CRUD model in favor of an action-oriented data access pattern, which this proposal seems to be counter to. 

There are a lot of ideas here. If you were to formalize a proposal, I suggest starting small with an incremental change which provides value at a lower change cost
