### ISSUE TITLE
GraphQL Logo License

### ISSUE THREAD

**Issue by lastmjs** [facebook/graphql#398]
I'm having trouble finding license information for the GraphQL logo. Does it exist somewhere? If not, any chance it could be CC0 like the [Redux logo](https://github.com/reactjs/redux/tree/master/logo#license)?

**Comment by astrocket** [comment]
+1

**Comment by leebyron** [comment]
Thanks for bringing this up - I'm not sure and I'll consult my favorite people who have opinions about this sort of thing.

**Comment by jwb** [comment]
Is the answer the same as the [license terms for using the React logo](https://github.com/facebook/react/issues/12570)?

**Comment by leebyron** [comment]
Unfortunately I'm not at Facebook anymore which makes answering this more challenging. @JoelMarcey could you help us investigate if the GraphQL logo can have a license similar to https://github.com/facebook/react/issues/12570?

**Comment by JoelMarcey** [comment]
Our open source logos fall under the same license as our documentation generally does -- Creative Commons 4.0 Attribution International. https://creativecommons.org/licenses/by/4.0/. However, there is an additional trademark consideration with our logos as well on their use.

**Comment by Daniel15** [comment]
I think this issue can be closed given @JoelMarcey's comment above.

**Comment by JoelMarcey** [comment]
Agree. 😄

**Comment by lastmjs** [comment]
I'm following up on trademark-specific questions here: https://github.com/graphql/graphql-spec/issues/822#issue-806772443

**Comment by gustavochermout** [comment]
Hello, I opened the issue: [#21190](https://github.com/facebook/react/issues/21190), because I have doubts about authorization for creating a community and using the logo.

I have doubts about CC 4.0 because of the part: "_Patent and trademark rights are not licensed under this Public License._".

@JoelMarcey could you say a little more about the comment: "there is an additional trademark consideration with our logos as well on their use."?

Does this mean that we can use the open source projects logo from facebook as long as we have given the proper attribution?

**Comment by benjie** [comment]
This was recently clarified in the docs, maybe the following help?

https://graphql.org/community/

https://lfprojects.org/policies/trademark-policy/

**Comment by JoelMarcey** [comment]
@gustavochermout These matters are now managed by the GraphQL Foundation. What I mentioned above was applicable when Facebook managed the GraphQL projects.

**Comment by gustavochermout** [comment]
Thank you very much for the answer @benjie, I didn't know that GraphQL is no longer managed by Facebook, so when I found an answer about Facebook's open source projects here, I thought I could get an overview of Facebook's open source projects. In this case I think I will need something more specific from Facebook, but thanks for the answer, it can help me in the future! :)

In this case @JoelMarcey, could you help me with this issue: [#21190](https://github.com/facebook/react/issues/21190)? As I would like to get more specific information about open source projects on facebook, maybe it is better to talk there in the React community.
