### ISSUE TITLE
Question: expected behavior for field arguments not defined in interface

### ISSUE THREAD

**Issue by tonyghita** [facebook/graphql#401]
I have a question about the following clause in the draft spec (under 3.1.2.3).

> The object field may include additional arguments not defined in the interface field, but any additional argument must not be required.

http://facebook.github.io/graphql/draft/#sec-Object-type-validation

What is the expected behavior of additional arguments that have a default value? For example:
```graphql
interface Namer {
  name: String!
}

type User implements Namer {
  id: ID!
  name(type: NameType = FULL): String!
  email: String!
}

enum NameType {
  FULL
  FIRST
  LAST
}
```

In this example, does `User` implement `Namer`?

**Comment by IvanGoncharov** [comment]
> In this example, does User implement Namer?

@tonyghita Yes it does. 
> What is the expected behavior of additional arguments that have a default value?

The only change that would break this rules is if you define `type` as `NameType!`.
See this PR for the explanation why this rule was added: https://github.com/facebook/graphql/pull/110

**Comment by IvanGoncharov** [comment]
> The object field may include additional arguments not defined in the interface field, but any additional argument must not be required.

Probably it makes sense to use [nullable](http://facebook.github.io/graphql/draft/#sec-Types.Non-Null) term and change it to `argument should be of a nullable type`.

@tonyghita What do you think?

**Comment by tonyghita** [comment]
@IvanGoncharov yes that clarifies the clause for me 💯%. Thank you for your response.
