### ISSUE TITLE
GraphQL is malformed JSON. Is it an issue or by design?

### ISSUE THREAD

**Issue by ksiv** [facebook/graphql#413]
GraphGL request is malformed JSON at same time response is OK. Since we get response in JSON, have to serialize our request to JSON to send and last but not least new JSON-like syntax brings nothing that JSON don't already provide, why not to use JSON?

I wonder, why nobody noticed it yet.

**Comment by IvanGoncharov** [comment]
> Is it an issue or by design?

@ksiv Yes, it is by design and documented here:
http://facebook.github.io/graphql/October2016/#sec-Language
GraphQL queries could be pretty complex, so they couldn't be easily described in JSON.
Here is a good tutorial explaining all things you can write inside query step by step:
http://graphql.org/learn/queries/

**Comment by tonyghita** [comment]
Maybe JSON is malformed GraphQL 🤔

**Comment by leebyron** [comment]
JSON and GraphQL are not the same and serve very different purposes - JSON to format data, GraphQL to format a request for data. Many GraphQL services respond to queries in JSON format, however the requests are made in the GraphQL language which is quite different, despite the similar `{ }` nesting (which is in fact designed to remind you of the resulting JSON payload).

**Comment by ksiv** [comment]
Don't want to be considered as a troll or something, but introducing something new very like something existing it's nice practice to show the advantages since you place on a techie guy one more abstraction with a payload that follows.  Could you point me to a best practices that shows clean advantage of GraphQL request over JSON. Thanks in advance!

**Comment by IvanGoncharov** [comment]
@ksiv Every technology has its design principles that result in Pros and Cons, e.g. PEP8. GraphQL has a similar list here:
http://facebook.github.io/graphql/October2016/#sec-Overview
> GraphQL is a query language designed to build client applications by providing an intuitive and flexible syntax and system for describing their data requirements and interactions.

Small example:
```graphql
# By default use id == 1
query getCharacterName($idArg: ID = 1) {
  person(id: $idArg) {
    name
  }
}
```
versus: 
```json
{
  "comment": "# By default use id == 1",
  "queries": [
    {
      "name": "getCharacterName",
      "args": {
        "idArg": {
          "type": "ID",
          "default": 1
        }
      },
      "selection": [
        {
          "field": "person",
          "args": {
            "id": {
              "ref": "idArg",
            },
          },
          "subSelection": [
            {
              "field": "name"
            }
          ]
        }
      ]
    }
  ]
}
```
Probably you can iterate on it make it smaller but JSON doesn't support:
 - comment
 - property arguments like: `person(ID: 2)`
 - variable references: `$idVar`
 - nice synctax for defaning query variable: `$idArg: ID = 1`.

If you add fragment definition, spreads, incline fragments to the mix it will make JSON even more unreadable.
So, in the end, it's not a JSON query it's JSON AST for GraphQL query language.

BTW. JSON AST is real thing you can use to manipulate your query, just call [parse](https://github.com/graphql/graphql-js/blob/81512407f8db5ac1fba1e59c4dce41c8feb68821/src/language/parser.js#L118-L122) from `graphql-js` or the same function in GraphQL implementation for your language of choice.

**Comment by ksiv** [comment]
Well it will take me more time to read through all sources like http://facebook.github.io/graphql/October2016/#sec-Overview
I do hope I will find something what could not be done say with JSON-RPC.
Thank you for your time

**Comment by IvanGoncharov** [comment]
> Well it will take me more time to read through all sources like 

@ksiv I meant only `Overview section`. If you want to read about all query features here is a good resource: http://graphql.org/learn/queries/

**Comment by ksiv** [comment]
@IvanGoncharov, maybe It just need a good real-life example?
Say I m a huge Bank&Oil M$$$  or a small web-shop or a Social Network. I do a JSON-RPC application, I have a JSON builder to make my request and a parser to read, the Idea of JSON here is serialization compact for transportation. JSON is and advantage in size over XML. So I use it, but I can do XML-RPC as well.
Say my endpoint is polymorphic and as a result it's at max flexible. So I can ask it it 
any RPC function with any amount of params and set of fields I ll need to be returned.  
I just fail to understand the advantages GraphQL will bring. 
And let us imagine I m not more a StartWar fan after new episode.
I v seen some more articles and still fail to understand how these items help to my business or my employer.
 - comment in the request (What's the point?)
 - nice syntax (matter of taste and it'll be generated by machine so I do not care)
 - property arguments, variable reference. (This one would make a point if covered by nice real world example of application)

See I really want to understand and employ this technology widely, Any help much appreciated. But maybe we just make it a time and some good examples will pop up eventually. 
Best wishes

**Comment by IvanGoncharov** [comment]
@ksiv As any other technology GraphQL has it's pros an cons. If you feel that XML-RPC or JSON-RPC better suits your project there is no reason to use GraphQL just because it's trending.

> * comment in the request (What's the point?)
> * nice syntax (matter of taste and it'll be generated by machine so I do not care)
> * property arguments, variable reference. (This one would make a point if covered by nice real world example of application)

GraphQL design goal is to create the language which is:
> intuitive and flexible syntax and system for describing their data requirements and interactions

So the idea here is that you don't use SDKs, class wrappers, etc but you write your queries by hand. If you feel like you don't agree with this design goal you can try http://jsonapi.org/ which provide an overlapping feature set with GraphQL but without inventing new syntax.

**Comment by ksiv** [comment]
>  but you write your queries by hand.
that's it!
that must be definitely the point.
I must came across misplacement of this technology it's used in client server communication in my current project that made me wondering why it's chosen here.
But it limits it full power to very rare occasion, I could only remember one place you can work manually with your queries and it would be Elastic.
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html
Still they make it JSON, but I remember a lot of handmade queries where it could be ok to go more human.
I remember about 15 years ago some scientist were provided SQL interface to work with data.
GraphQL might success in these application
