### ISSUE TITLE
@include or @skip directives with string comparison

### ISSUE THREAD

**Issue by romeboards** [facebook/graphql#414]
I'm looking to create a GraphQL query that selectively adds/removes fields based on a variable "type", which is a string:

`query ResultsPage($casetype: String!)`

According to the reference on Directives, you can use a boolean value to either @include or @skip certain fields:

```
query Hero($episode: Episode, $withFriends: Boolean!) {
  hero(episode: $episode) {
    name
    friends @include(if: $withFriends) {
      name
    }
  }
}

```
How could I do something similar with this string value? i.e. only include the friends field if $casetype = "foo". What is the best way to approach this problem using GraphQL?

Thanks!

**Comment by IvanGoncharov** [comment]
@romeboards GraphQL is designed to be as simple as possible so it doesn't support constructions from programming languages, e.g. comparations.
So you can include/exclude fields only based on the boolean query parameters.
But as I understand, you want to change query result based value of enum which is not possible according to GraphQL spec.

So can you please describe your use case in more details?
Mainly, how is your schema looks like and why your frontend needs different responses?

**Comment by leebyron** [comment]
Closing this aging issue.

To answer the question directly - GraphQL does not support conditions like this. Multiple booleans may be a fit for your use case

**Comment by sgleske-ias** [comment]
In my case of using GitHub graphql, I'm interested in the listing of a Tree (folder) and want to only read the contents of a specific file in that tree.  However, my current option is to read every file in that tree.

**Comment by aminnoura** [comment]
I want to get all the orders which has status of 'ACCEPTED'
is that possible?

**Comment by id-ilych** [comment]
Hello @aminnoura :wave:
Sounds like you need to make it an argument so that the query will look like
```graphql
query ($cursor: String) {
  orders(
    filter: {status: ACCEPTED}
    pagination: {first: 20 after: $cursor}
  ) {
    edges { 
      node { ... }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
```

So that you can both filter orders with specific properties and do the pagination (there may be a lot of them, right?)

**Comment by xmlking** [comment]
I need to update  two related objects (`Policy` 1->* `Rules`) conditionally on one call. I want to **skip** `update_rules_by_pk` part if   **$ruleId** or **$ruleData** are null/undefined.
I understand **@skip/@include** directives works with Boolean only. 
Is this a fair use case to ask support for more options for  **@skip/@include** directives?  

```gql
mutation UpdatePolicy($policyId: uuid!, $policyData: policies_set_input!, $ruleId: uuid!, $ruleData: rules_set_input) {
  update_policies_by_pk(pk_columns: {id: $policyId}, _set: $policyData) {
    id
    updatedAt
  }
  update_rules_by_pk(pk_columns: {id: $ruleId}, _set: $ruleData) @skip(if: { ruleData: { _eq: null } }  ) {
    id
    displayName
    updatedAt
  }
}
```
payload 
```json
{
  "policyId": "9bd4e02e-9255-4107-b7cb-7c849888cd1b",
  "policyData": {
    "active": true,
    "validFrom": "2023-06-28T17:22:00.000Z",
    "validTo": "2023-06-30T17:22:00.000Z",
    "weight": 677
  },
  "ruleId": "ff9cf187-6c4b-4fd5-aa6d-25c40980453e",
  "ruleData": {}
}
```

**Comment by xmlking** [comment]
I could use following  solution but with extra code complexity. Natural way to do this is if `ruleData` empty, then skip updating Rule.
```gql
mutation UpdatePolicy(
	$policyId: uuid!
	$policyData: policies_set_input!
	$ruleId: uuid!
	$ruleData: rules_set_input!
	$skipRule: Boolean = false
) {
	update_policies_by_pk(pk_columns: { id: $policyId }, _set: $policyData) {
		id
		subjectDisplayName
                updatedAt
	}
	update_rules_by_pk(pk_columns: { id: $ruleId }, _set: $ruleData) @skip(if: $skipRule) {
		id
		displayName
                 updatedAt
	}
}
```
```json
{
  "policyId": "9bd4e02e-9255-4107-b7cb-7c849888cd1b",
  "policyData": {
    "active": true,
    "validFrom": "2023-06-28T17:22:00.000Z",
    "validTo": "2023-06-30T17:22:00.000Z",
    "weight": 677
  },
  "ruleId": "ff9cf187-6c4b-4fd5-aa6d-25c40980453e",
  "ruleData": {},
  "skipRule": true
}
```
