### ISSUE TITLE
Acknowledgement of messages in Subscription 

### ISSUE THREAD

**Issue by senthilsivanath** [facebook/graphql#419]
Subscription allows client to get messages when they appear, but in case of failures client do not have the option to ack / nack (to skip) messages. 

This allows the replay of messages 
Better transaction handling

Simply Put : Exposing kakfa via graphql schema

**Comment by NatashaB84** [comment]
Exposing kakfa via graphql schema

**Comment by leebyron** [comment]
GraphQL is on a different layer of abstraction from message delivery. GraphQL only represents the request for and sequence of a message stream.

You might layer GraphQL subscriptions over Kafka or some other protocol-level service to get the QoS you need.
