### ISSUE TITLE
Whitespace treatment in grammar

### ISSUE THREAD

**Issue by OlegIlyenko** [facebook/graphql#42]
Please correct me if I missed it in the spec, but I haven't found a formal definition of the whitespace treatment combined with some of the tokens. For example in the [detective definition](http://facebook.github.io/graphql/#sec-Syntax.Directives). It's not 100% clear whether whitespace is allowed between `@` and `Name`. The same is for the [variable](http://facebook.github.io/graphql/#sec-Syntax.Operations): can I put a whitespace between `$` and the `Name` like this?

    $ myVariable

Intuition tells me that in most cases whitespaces are allowed, so query like this:

    query    , FetchLukeAndLeiaAliased{
      luke:human(id   :  2.1e-7) {
        name,
      }
      leia       ,  : human   ,,, ( , id ,, : ,, "10103") {
        name
      }
    }

is a valid query and should be parsed without any errors. Is my assumption correct?

**Comment by devknoll** [comment]
[8.1.1](http://facebook.github.io/graphql/#sec-Ignored-Source) says *Whitespace, other than within strings, is not significant*. Your assumption should hold.

**Comment by leebyron** [comment]
You're correct. Anything defined as a token grammar (consumes characters) is sensitive to whitespace (eg, string and number literals). Anything defined as a syntax grammar (consumes tokens) is not sensitive to whitespace or other ignored characters. 

I'll try to clarify this in the spec
