### ISSUE TITLE
Question: difference between comments and descriptions?

### ISSUE THREAD

**Issue by tonyghita** [facebook/graphql#420]
Previous to merging descriptions into the specification, we used [comments](http://facebook.github.io/graphql/draft/#sec-Comments) to document each field and type. 

Does the introduction of [descriptions](http://facebook.github.io/graphql/draft/#sec-Descriptions) deprecate the old functionality of comments? If so, what is the intended usage of comments? If not, what is the difference between comments and descriptions?

**Comment by IvanGoncharov** [comment]
> Does the introduction of descriptions deprecate the old functionality of comments?

@tonyghita Yes it does.

> If so, what is the intended usage of comments?

```graphql
type Person {
  """name of a person"""
  name: String
  #TODO: Add surname

  # FIXME: Commented due to crash
  # avatarUrl: String
}
```
So comments are completely ignored by GraphQL. They even skipped by parser so it makes them equivalent to whitespaces.

You can read about this change in more details here: https://github.com/graphql/graphql-js/pull/927
If you have time and want to understand the motivation behind this change here is the relevant thread: https://github.com/facebook/graphql/pull/90#issuecomment-254995574

**Comment by tonyghita** [comment]
Thanks for the clarification and references @IvanGoncharov  👍

**Comment by marcospgp** [comment]
Time to update the docs with this info :) I can't see it anywhere here: https://graphql.org/learn/schema/#the-query-and-mutation-types

I seem to only be able to find it on unofficial resources. Cheers!

**Comment by lorensr** [comment]
`graphql-tools` treats comments (`#`) as descriptions, in addition to `"` and `"""`:

```gql
"""
comment 1
"""
type Query {
  # comment 2
  hello(
    "comment 3"
    name: String
  ): String
}
```

Comments can be written in Markdown. Spec section on descriptions: http://spec.graphql.org/draft/#sec-Descriptions
