### ISSUE TITLE
Pls, add a Separator into Schema documentation. (Accordion like)

### ISSUE THREAD

**Issue by MichelDiz** [facebook/graphql#425]
When we have a big API, with several functions. We have a gigantic documentation of Schema with queries, mutations and subscriptions. So, this gets complicated and confusing with time because of the order of things.

A separator in sessions besides the own comments with something like "Accordion"  would be perfect.

Cheers.

**Comment by leebyron** [comment]
Sorry, I'm not sure what you're suggesting. Perhaps you have the wrong repo? 

I'm closing this issue, but if you like please reopen with a suggested specification text change?

**Comment by MichelDiz** [comment]
I wrote here because I thought it was your team who supported "GraphiQL". To have something like "Accordion" would need to create something in the graphql syntax to get such a feature. I'm wrong?

**Comment by remyrylan** [comment]
@MichelDiz try posting an issue on the GraphiQL repo, this repo is for the GraphQL spec, GraphiQL (with the "I")  is the IDE.

**Comment by MichelDiz** [comment]
I know that, I think you didn't understand my point. The IDE will be irrelevant if there is no specification in the GraphQL syntax. Did you get it?
