### ISSUE TITLE
Proposal: arguments shorthands `posts($q, $limit)`

### ISSUE THREAD

**Issue by caub** [facebook/graphql#426]
Similarly to JS's shorthand object props/destructuring, I'd like to propose to write queries either like:

```graphql
{
  posts($q, $limit) {
    id
    content
  }
}
```
or more simply:
```graphql
{
  posts(q, limit) {
    id
    content
  }
}
```
instead of the current
```graphql
{
  posts(q: $q, limit: $limit) {
    id
    content
  }
}
```

They require to fit the models arguments and have corresponding variables:
```json
{
  "q": "Foo bar ...",
  "limit": 10
}
```

**Comment by caub** [comment]
Also I find it really verbose to do 
```graphql
query Foo($id: ID!) {
  foo(id: $id) {
    name
    description
  }
}
```
the shorthand argument wouldn't simplify it much:
```graphql
query Foo($id: ID!) {
  foo($id) {
    name
    description
  }
}
```
My problem is with the query (or mutation, or subscription) wrapper. I understand it's good to put the type constraint only once, I can't see a better way though

**Comment by leebyron** [comment]
Merging into #411

**Comment by obedm503** [comment]
This proposal is different from #411. This is not about positional arguments.
```gql
query Foo($text: String!, limit: Int!) {
  foo(text: $text, limit: $limit) {
    ...
  }
}
```
could be 
```gql
query Foo($text: String!, limit: Int!) {
  foo($text, $limit) {
    ...
  }
}
```
or
```gql
query Foo($text: String!, limit: Int!) {
  foo($limit, $text) {
    ...
  }
}
```
regardless of the argument order.

As @caub proposes this is inspired by ES2015's object literal property shorthand. It is completelly independent from positional arguments.

**Comment by sungam3r** [comment]
> This proposal is different from #411. This is not about positional arguments.

Agree.
