### ISSUE TITLE
Trouble with graphql orderBy

### ISSUE THREAD

**Issue by kierah** [facebook/graphql#427]
I have a query that works well unordered. 
```
query feedQuery {
  allPostsFromAllBlogs
  {
    id
    blogId
    title
    text
    likes
    createdAt
  }
}
```
I want to sort the results (of type [Post]). This is the query I'm using to do that:
```
query feedQuery {
  allPostsFromAllBlogs( orderBy: {field: createdAt, direction:DESC}) 
  {
    id
    blogId
    title
    text
    likes
    createdAt
  }
}
```
Which produces this output in graphiql:
```
{
  "errors": [
    {
      "message": "Unknown argument \"orderBy\" on field \"allPostsFromAllBlogs\" of type \"Query\".",
      "locations": [
        {
          "line": 2,
          "column": 25
        }
      ]
    }
  ]
}
```

I'm not sure what other information you would need to diagnose the problem, but I assume its a query syntax error. 

Why is it not recognizing orderBy?

**Comment by IvanGoncharov** [comment]
> Why is it not recognizing orderBy?

@kierah It's very likely that particular API you are trying to use doesn't support `orderBy` argument. By itself, GraphQL doesn't provide `orderBy` or any other arguments so if needed they should be implemented by API author.
Please contact API author to solve your problem.

**Comment by kierah** [comment]
@IvanGoncharov 
I am using apollo. Are they the right ones to ask?

**Comment by IvanGoncharov** [comment]
> I am using apollo. Are they the right ones to ask?

If they are authors of this particular API then yes.

**Comment by stubailo** [comment]
This also isn't built into Apollo :]

**Comment by kierah** [comment]
Ah ok thank you very much for the responses
