### ISSUE TITLE
Ellipsis char

### ISSUE THREAD

**Issue by OlegIlyenko** [facebook/graphql#43]
Does grammar allow [Unicode 'HORIZONTAL ELLIPSIS' char (U+2026)](http://www.fileformat.info/info/unicode/char/2026/index.htm) as a substitute for 3 consequent dots? If yes, then it would be nice to have this fact explicitly stated in the spec.

**Comment by leebyron** [comment]
It does not, it expects three \u002E period characters.

**Comment by OlegIlyenko** [comment]
Thanks!
