### ISSUE TITLE
Proposal: rename `@skip` to `@exclude`

### ISSUE THREAD

**Issue by ianstormtaylor** [facebook/graphql#430]
Right now there are only two directives in core: `@include` which ignores fields if true, and its exact opposite... `@skip`. But `@skip` is poorly named because it's not the parallel opposite word. It should really be named `@exclude` to make the API more consistent and intuitive.

I realize this isn't giving us new functionality, and it's one of many small things, but it would just be nice from a design and consistency standpoint.

**Comment by leebyron** [comment]
While I appreciate and agree with your suggestion, the `@skip` directive has been in the spec for a number of years and the cost of changing this for all existing implementors is too high.

You're always more than welcome to include additional directives with whatever behavior you like, including aliases for the specified directives
