### ISSUE TITLE
Proposal: Object serialization

### ISSUE THREAD

**Issue by SerafimArts** [facebook/graphql#431]
I propose the possibility of serializing composite types (like Object) into scalar values. This functional will be useful in those cases when some object can be represented in a scalar value, but it provides (can) a functional (a set of fields).

We can use the name `__toScalar` field as the serializable value name. Double underline at the beginning is compatible with the standard adopted for system names.

For example:

## Definition

```graphql
type DateTimeObject {
    year: Int!
    month: Int!
    # ...
    ago: String!
    format(format: String!): String!
    __toScalar: DateTime!
}
```

### As Object

```graphql
{
    date {
        year
        month
    }
}
```

```json
{
    "date": {
        "year": 2018,
        "month": 04
    }
}
```

### As Scalar

```graphql
{
    date # __toScalar field usage
}
```

```json
{
    "date": "2018-04-28T04:53:23+03:00"
}
```

**Comment by leebyron** [comment]
I'd prefer to avoid the type of a field changing based on how its queried. That greatly limits the power available to tools, especially smart clients like Relay and Apollo. 

I think this also introduces a serious foot-gun where a query that previously would clearly be a validation error now returns a value, however its not clear that the user intended on the new usage and may result in a hard-to-spot error in their software.

An alternative to this which should work today is simply to provide a field like this (maybe without the underscores, which are system-reserved) and explicitly query it:

```graphql
type DateTimeObject {
    year: Int!
    month: Int!
    # ...
    ago: String!
    format(format: String!): String!
    toScalar: DateTime!
}
```

### As Scalar

```graphql
{
    date { 
      toScalar 
    }
}
```

```json
{
    "date": {
      "toScalar": "2018-04-28T04:53:23+03:00"
    }
}
```
