### ISSUE TITLE
No helpful error when resolver is missing

### ISSUE THREAD

**Issue by vjsingh** [facebook/graphql#444]
I'm just getting into GraphQL. I wrote some code that was missing a resolver. When I tried to query for it, I just got back a null value. Perhaps GraphQL could output a more helpful error in these cases either in the browser or in the server console?

**Comment by juancampa** [comment]
Having no resolver is not considered an error because it defaults to the "default resolver"

Here's more info: https://www.apollographql.com/docs/graphql-tools/resolvers#Default-resolver

**Comment by vjsingh** [comment]
I see. That makes sense for non-root-level resolve functions.

Is there a default behavior for root-level resolve functions?

**Comment by IvanGoncharov** [comment]
@juancampa You absolutely right and thanks a lot for the detailed explanation 👍 

> Perhaps GraphQL could output a more helpful error in these cases either in the browser or in the server console?

@vjsingh As @juancampa explained above it's impossible to detect such cases without limiting `graphql-js` flexibility.

Also please note this repo is intended for GraphQL specification so if you found a bug or want to submit feature requests related to `graphql-js` please open issues here: https://github.com/graphql/graphql-js

**Comment by vjsingh** [comment]
Got it. Thanks @juancampa  and @IvanGoncharov for the info. I'll direct further questions to graphql-js
