### ISSUE TITLE
Missing mention of Type can only refer to Input Object types in field arguments

### ISSUE THREAD

**Issue by tinganho** [facebook/graphql#447]
In the section 3.6.1 Field Arguments: http://facebook.github.io/graphql/draft/#sec-Field-Arguments

>Object fields are conceptually functions which yield values. Occasionally object fields can accept arguments to further specify the return value. Object field arguments are defined as a list of all possible argument names and their expected input types.

>All arguments defined within a field must not have a name which begins with "__" (two underscores), as this is used exclusively by GraphQL’s introspection system.

>For example, a Person type with a picture field could accept an argument to determine what size of an image to return.

It misses to mention that if a `Type` is a `NamedType` it can only refer to the name of an input object type.

**Comment by IvanGoncharov** [comment]
> It misses to mention that if a Type is a NamedType it can only refer to the name of an input object type.

@tinganho Actually no, also you can use scalars both standard (String, Int, ...) and custom. That's why specification uses `input type` term for everything that can be used as an argument:

> list of all possible argument names and their expected input types.

**Comment by leebyron** [comment]
I think we mention this elsewhere, but it's hard to find a consistent reference to link to which I think we should improve
