### ISSUE TITLE
GraphQL website: SSL certificate has expired

### ISSUE THREAD

**Issue by raulk** [facebook/graphql#448]
The certificate expired on May 23rd at 17:52 WEST. Screenshot:

![image](https://user-images.githubusercontent.com/1101242/40486961-a5f5ad86-5f5a-11e8-8091-3c411aab1d56.png)

**Comment by IvanGoncharov** [comment]
@raulk Looks like it was fixed 🎉 
![image](https://user-images.githubusercontent.com/8336157/40729580-58bcc740-6435-11e8-8873-d76e2522d0e2.png)

**Comment by kolobock** [comment]
starts to reproduce again after one year

**Comment by benjie** [comment]
Raised in WG repo: https://github.com/graphql/graphql-wg/issues/176
