### ISSUE TITLE
The graphql.org domain points to a 404

### ISSUE THREAD

**Issue by SaitamaSama** [facebook/graphql#449]
Opening http://graphql.org/ it points to a 404. So essentially all the links to the pages in `http://graphql.org/*` are dead.

**Comment by jcward** [comment]
404's and github "not found" pages... :frowning_face: Also, trying to access google's cached version doesn't work.

**Comment by jcward** [comment]
FYI, seems like site is back up with newly valid SSL (#448). :+1:
