### ISSUE TITLE
Input type variable not working with query

### ISSUE THREAD

**Issue by PiotrSzlagura** [facebook/graphql#457]
#Hello, I have an issue which might not be directly related to GraphQL but I don't know where else I could go with it, so if you could show me some direction, that would be fantastic.

My issue:
I have following input type defined:
```graphql
input ProductFilterInput {
   price: FilterTypeInput
   name: FilterTypeInput
   ...
}
```
and my query looks like:
```graphql
query GetProductsQuery($page: Int, $filterInput: ProductFilterInput){
  products(
    pageSize: 10
    currentPage: $page
    filter: $filterInput
    sort: {}
  ) {
    items {...}
  }
}
```

It should work but instead I receive two errors:
```
Variable "$filterInput" of type "ProductFilterInput" used in position expecting type "ProductFilterInput".
```
and
```
Variable "$filterInput" cannot be non-input type "ProductFilterInput".
```

Back-end is Magento 2.3 with recently added graphql support

EDIT:
The same happens when I try passing enum as variable:
```
Variable "$priceSortDir" of type "SortEnum" used in position expecting type "SortEnum"
```

EDIT 2:
Passing simple values (like Int, String) works fine

EDIT 3 (last):
I just tested this approach on clean installation of GraphQL and everything works fine, so it seems that this issue is related with Magento 2.3.

**Comment by IvanGoncharov** [comment]
> I just tested this approach on clean installation of GraphQL and everything works fine, so it seems that this issue is related with Magento 2.3.

You probably right, your query looks good and errors are strange.

> Hello, I have an issue which might not be directly related to GraphQL but I don't know where else I could go with it

You try posting a question on StackOverflow.

This repo is intended to discussing changes to GraphQL Specification so I closing this issue.
