### ISSUE TITLE
14.0.0-rc.1. Was this a mistake?

### ISSUE THREAD

**Issue by ethanneff** [facebook/graphql#458]
From `0.13` to `14.0`, was this a versioning mistake?
Pulling from npm https://www.npmjs.com/package/graphql

```
graphql  ^0.13.2  →  ^14.0.0-rc.1
```

**Comment by IvanGoncharov** [comment]
No, it was planned long ago:
https://medium.com/@leeb/graphql-js-preparing-for-v14-0-0-839f823c144e
