### ISSUE TITLE
Fragment directive overriding is underspecified

### ISSUE THREAD

**Issue by swolchok** [facebook/graphql#46]
The Fragment Directives section says that "At runtime, the directives provided on a fragment spread override those described on the definition.", but "override" here is not sufficiently precise. Consider the following example:

```
query example { ...F @bar }
fragment F on Query @foo { some_field }
```

Is this equivalent to using both `@foo` and `@bar` or just `@bar`? (Presumably, "neither" and "just @foo" wouldn't be consistent with "override.") Does it matter if `@bar` and `@foo` have any kind of interaction in their effects?

**Comment by swolchok** [comment]
Oh, there is a formalism `FragmentSpreadDirectives` that answers this. It could really be incorporated into the text better.

**Comment by leebyron** [comment]
Leaving it open as a note to improve the text

**Comment by IvanGoncharov** [comment]
@swolchok This section was removed in 1c38e6ac16de82a2a28487c8f193d673e39a1e33:
> In addition, this changes the specification of the `@skip` and `@include` directives to no longer allow their use on fragment directives (but are still allowed on fragment spreads and inline fragments). Because of this, a section on "merging fragment directives" is no longer useful.
