### ISSUE TITLE
GraphQL.org is in infinite redirect loop

### ISSUE THREAD

**Issue by nkconnor** [facebook/graphql#474]
Wasn't sure where to put this.. but it seems http redirects to https and vice versa

**Comment by michaelstaib** [comment]
I think you should file an issue here -> https://github.com/graphql/graphql.github.io/issues

**Comment by michaelstaib** [comment]
There is already a redirect loop issue on graphql.github.io https://github.com/graphql/graphql.github.io/issues/516

So this one could be closed.

**Comment by nkconnor** [comment]
Thanks. Also fixed now I believe
