### ISSUE TITLE
Input object directive argument

### ISSUE THREAD

**Issue by tinganho** [facebook/graphql#481]
I'm writing a parser for GraphQL. I noticed according the spec, that GraphQL allows input object arguments on directives:

```gql
input InputObject {
    field: Int
}

directive @directive(argument: InputObject) on OBJECT
```
I'm just wondering if there is any valid use case, to allow input objects? I'm considering dropping support for it, if there aren't any.

Sorry, if I post on wrong forum. I don't know any better place to ask than here.

**Comment by stubailo** [comment]
Absolutely there are! They are used in lots of custom directives. The GraphQL spec only specifies skip, include, and deprecated, but there might potentially be many others. For examples, see:

- GraphQL Lodash: https://github.com/APIs-guru/graphql-lodash
- Custom schema directives in Apollo Server/graphql-tools: https://www.apollographql.com/docs/apollo-server/v2/features/directives.html

Basically it depends on if you want users of your parser to be able to define custom directives of any kind.

**Comment by tinganho** [comment]
I couldn't find any example with an object as argument. But I think I will implement it anyway. Thanks.
