### ISSUE TITLE
Proposal: Add some markdown from comments

### ISSUE THREAD

**Issue by iamclaytonray** [facebook/graphql#482]
Could we support some markdown in GraphQL comments? The benefit is not huge and is definitely the lowest priority issue on here but this proposal could make sense in some contexts. I could possibly want to put emphasis on a certain part of a comment so that other people who read the docs for my API don't overlook it. That's about as far as I got with thinking this through. I have an example below but it's pretty simple. I would imagine that this is a pretty easy job and I'd be willing to shoot a PR over to `graphql-js` if accepted.

Obviously, it probably wouldn't be a wise idea to have full support for Markdown. I was thinking of:

- Italics
- Bold
- Strikethrough
- Links (maybe)

For example:

```graphql
enum MessageStatus {
  # If a message could not successfully be delivered.
  Failed
  # If a message was successfully delivered but _has not been_ read by the other user(s).
  Delivered
  # If a message was successfully delivered and _has been_ read by the other user(s).
  Read
}
```

Could possibly return the following in the docs:

If a message could not successfully be delivered.
If a message was successfully delivered but **has not been** read by the other user(s).
If a message was successfully delivered and **has been** read by the other user(s).

**Comment by IvanGoncharov** [comment]
@iamclaytonray GraphQL already supports full CommonMark (a dialect of Markdown):
http://facebook.github.io/graphql/June2018/#sec-Descriptions
>To allow GraphQL service designers to easily publish documentation alongside the capabilities of a GraphQL service, GraphQL descriptions are defined using the Markdown syntax (as specified by CommonMark).

Note: that SDL syntax was changed during preparation for public release so in final version you need to use description strings instead of comments and now comments are just comments:
```graphql
enum MessageStatus {
  "If a message could not successfully be delivered."
  Failed
  "If a message was successfully delivered but _has not been_ read by the other user(s)."
  Delivered
  # TODO: add write
  "If a message was successfully delivered and _has been_ read by the other user(s)."
  Read
}
```
