### ISSUE TITLE
Int type value in enum type

### ISSUE THREAD

**Issue by zhewang2** [facebook/graphql#487]
I was trying to create an enum type with Int value in GraphQL schema but failed. I might miss something in the doc. Anyone has any idea about how to implement Int value in the enum type like below?

enum IntValue {
  1
  2
  3
}

**Comment by IvanGoncharov** [comment]
@zhewang2 You can't, enum values should start from a letter or underscore:
http://facebook.github.io/graphql/June2018/#sec-Names

> Anyone has any idea about how to implement Int value in the enum type like below?

Enum values are always strings.

**Comment by zhewang2** [comment]
@IvanGoncharov  Thank you for your replying! It is very helpful!

**Comment by shankwiler** [comment]
Updated link to the above http://spec.graphql.org/June2018/#sec-Names
