### ISSUE TITLE
does ObjectValue support double-quote or single-quote as like JSON object token?

### ISSUE THREAD

**Issue by pli2014** [facebook/graphql#491]
![image](https://user-images.githubusercontent.com/6429799/43755575-1a2b7118-9a43-11e8-8550-e6045fa4bea1.png)

From this spec, I cannot find this declaration for this issue, what have to be considered about this? 
refer to :http://facebook.github.io/graphql/June2018/#ObjectField

**Comment by IvanGoncharov** [comment]
> does ObjectValue support double-quote or single-quote as like JSON object token?

Neither, just write names without any quote e.g. `{ a: 1, b: 2 }`
