### ISSUE TITLE
[RFC]  Dynamic Directive Variables On Server Side

### ISSUE THREAD

**Issue by imiskolee** [facebook/graphql#497]
# Dynamic Directive Variables

## Background

As well as we know, we can apply directive and pass variables for each query/mutation/field, But can't share variable from runtime(query's variable or global request variables).

Maybe we can support share variables for directive for handle this.

## Proposed solution

1. support share variable definition syntax.  like：

```graphql
query {
findMyResource(userID:Int) @hasPermission($userID)
}
```
The above example is showing how to define share variable syntax.

## Full Example

```graphql
directive @hasPermission(userID:Int)
type Query  {
       findMyResource(userID:Int) @hasPermission($userID)  #directly ref variable
       findMyResourceFor
}
type Mutation {
	editMyResource(user:User) @hasPermission($user.id) # ref object's field
}
```

** I am talking automatic apply directive on server side. thanks!**

**Comment by IvanGoncharov** [comment]
@imiskolee Maybe I'm missing something but why you can't write:
```graphql
query ($userID: Int) {
  findMyResource($userID) @hasPermission($userID)
}
```
You can use query variables inside fragments it's perfectly legal.

**Comment by IvanGoncharov** [comment]
@imiskolee In that case, your examples from a first comment are very confusing.
`query {` is a beginning of the client-side query, e.g. `query { __typename }`.
Is it just a typo and it should be `type Query {`?

**Comment by imiskolee** [comment]
@IvanGoncharov yes.

**Comment by imiskolee** [comment]
@mjmahone  yes! you're right. we don't need support dynamic variable. just make a way to pass the `user.id` path into directive.

thanks!  I will close it.
