### ISSUE TITLE
Is a dynamic field-return-type possible with GraphQL? 

### ISSUE THREAD

**Issue by Patrick-Spiegel** [facebook/graphql#501]
In many object orientated programming language we have the idea of a base type which all other types derive from. 

If you have a field which returns an object value, how could it be possibly done in a GraphQL schema? afaik there is not such a thing like object or any. Therefore it is only possible to return either an int, a floating point value or a string, but not dynamically any of them dependent on the sources type.

**Comment by IvanGoncharov** [comment]
> If you have a field which returns an object value, how could it be possibly done in a GraphQL schema? afaik there is not such a thing like object or any. Therefore it is only possible to return either an int, a floating point value or a string, but not dynamically any of them dependent on the sources type.

All custom scalars behave like that:
http://facebook.github.io/graphql/June2018/#sec-Scalars
If you asking specifically for `Any` it's already proposed and discussed in #325 PR.
