### ISSUE TITLE
Enforce HTTPS for github.io pages?

### ISSUE THREAD

**Issue by maantje** [facebook/graphql#503]
At the moment HTTPS is not forced for http://graphql.github.io/ and http://facebook.github.io/graphql/ the GraphQL readme even links to the "unsecure" http://facebook.github.io/graphql/.

Would it not be cleaner if http://graphql.github.io/ and http://facebook.github.io/graphql/ were forced over [HTTPS](https://help.github.com/articles/securing-your-github-pages-site-with-https/)?

**Comment by IvanGoncharov** [comment]
> the GraphQL readme even links to the "unsecure" http://facebook.github.io/graphql.

Do you want to make PR for that?
Also note there are some `http` URLs in spec text and would be great to fix them all in a single PR.

**Comment by maantje** [comment]
> Do you want to make PR for that?

Sure, ill make a PR.

**Comment by JoelMarcey** [comment]
I believe I have fixed these. Let me know if they are not redirecting. Thanks.

**Comment by leebyron** [comment]
Thanks, Joel!
