### ISSUE TITLE
Union type validation talks about inputs, but unions are never valid inputs

### ISSUE THREAD

**Issue by swolchok** [facebook/graphql#51]
The last paragraph of this section: http://facebook.github.io/graphql/#sec-Union-type-validation

> When expected as an input type, array input values are accepted only when each item in the input array can be accepted by the item type. If the input value is not an array but can be accepted by the item type, it is coerced by creating an array with the input value as the sole item. Other input values must raise a query error indicating an incorrect type.

Is this paragraph misplaced?

**Comment by leebyron** [comment]
Indeed it was!
