### ISSUE TITLE
How to custom errors?

### ISSUE THREAD

**Issue by KeatingSmith** [facebook/graphql#513]
Example:

GraphQL:

```json
{
  "errors": [
    "Some erros"
  ],
  "data": null
}
```

I think it`s not awesome, so I want to custom my own format.

```json
{
  "errors": {
     "message": "some errros",
     "time": "2018-09-10 18:00",
  },
  "data": null
}
```

How to do it?

**Comment by jlouis** [comment]
In the GraphQL specification, Jun2018, there is now provisioning for adding your own error-data:

http://facebook.github.io/graphql/June2018/#sec-Errors

In your case, the `errors` *must* be an array `[E1, E2, ...]` where each `Ei` contains:

```
{
  "message": "Your error description"
  "extensions": {
     "time": "2018..."
  }
}
```

Your custom data should go into `extensions`. The reason for this is that top level naming scheme is something GraphQL "owns" and has responsibility for, whereas `extensions` is something you own and can extend as you see fit.

This way, a GraphQL client has some data it inherently *knows* are present and that it can use (`message`, `path`, `key`, ...), and something which you can use to add your own timestamp, request_id, error code and so on.

This repository mostly has to do with the specification parts of GraphQL. For a given implementation, it is probably better to open an issue in their respective bug-tracker, eventually referring to the above section in the specification.

**Comment by IvanGoncharov** [comment]
@jlouis Thanks a lot for such detail answer 👍 
I think we need to create FAQ at some point and your answer is an ideal fit for it.
