### ISSUE TITLE
Problem with user query

### ISSUE THREAD

**Issue by fabiosferreira** [facebook/graphql#516]
I'd like to retrieve users data from the the GraphQL API v4 but I have found problems in some cases. For example, the query bellow returns the message **Could not resolve to a User with the login of 'ReactiveX'**:
```
{
  user (login:"ReactiveX"){
            name
  }
}
```

If I use the REST API v3, the data are retrieved normally.

`https://api.github.com/users/ReactiveX`

**Comment by IvanGoncharov** [comment]
@fabiosferreira It's a repo for GraphQL specification in general and not a particular API. If you want to ask a question about GraphQL API implemented by GitHub please do it here: https://github.community/t5/GitHub-API-Development-and/bd-p/api

**Comment by fabiosferreira** [comment]
I'm sorry @IvanGoncharov. Thank you very much!
