### ISSUE TITLE
Allow "." in operation name

### ISSUE THREAD

**Issue by raderio** [facebook/graphql#547]
At the moment we can name our operation by a name only /[_A-Za-z][_0-9A-Za-z]*/.
Is it possible to allow also the dot "." ?

So, before
```
query usersList {hello}
```
after 
```
query users.list {hello}
```
The dot is using as a namespace delimiter.

this will allow to generate a documentation like
https://api.slack.com/methods
https://vk.com/dev/methods

**Comment by IvanGoncharov** [comment]
@raderio Operation names used in code generation to generate a function that sends the query or to create type definition of the response.
For example [HeroName operation](https://github.com/apollographql/apollo-tooling/blob/master/packages/apollo-codegen-typescript/src/__tests__/codeGeneration.ts#L48) produceses [Hero Name TS type](https://github.com/apollographql/apollo-tooling/blob/master/packages/apollo-codegen-typescript/src/__tests__/__snapshots__/codeGeneration.ts.snap#L91-L93).
Names with letters, numbers and underscore is biggest common subsets that supported in all programming languages.

Can you please describe your use case and provide argumentation acording to "Favor no change" principle:
> As GraphQL is implemented in over a dozen languages under the collaboration of hundreds of individuals, incorporating any change has a high cost. Accordingly, proposed changes must meet a very high bar of added value. The burden of proof is on the contributor to illustrate this value.

P.S. Don't forget you can use underscore, e.g. `users_list`.

**Comment by IvanGoncharov** [comment]
@raderio If you want this issue to reopen please feel free to ping me.
