### ISSUE TITLE
Set Type?

### ISSUE THREAD

**Issue by khteh** [facebook/graphql#548]
W.r.t https://github.com/facebook/graphql/issues/101, what's the equivalent schema datatype for Set? I am using GraphQL for Java. Thanks.

**Comment by IvanGoncharov** [comment]
@khteh Same as JSON you can use arrays to represent `Set`.

> I am using GraphQL for Java. 

If you want more details on how to do this Java please ask a question on StackOverflow or in the repo of graphql library that you are using.
