### ISSUE TITLE
type vs input

### ISSUE THREAD

**Issue by raderio** [facebook/graphql#549]
I don't get it, why there are 2 kinds of type: `type` and `input`?
Why just not to have one keyword `type`?

For example we have type
```
type GeoLocation {
    latitude: Float!
    longitide: Float!
}
```
Why we also need an `input` with the same content?

If the reason is that for input and output we need different types, than let's have 2 types `type XyzInput` & `type XyzOutput`.

**Comment by IvanGoncharov** [comment]
@raderio Input and Output types are fundamentally different. Output types are [nominal typed](https://en.wikipedia.org/wiki/Nominal_type_system) but input types are [duct typed](https://en.wikipedia.org/wiki/Duck_typing).

Also, there are some other discrepancies e.g. input objects can't have arguments.

**Comment by raderio** [comment]
What do you mean by input types are duck typed?
Why that types cannot be validate on using and not on declaration? If type is not using as input than it's ok.

**Comment by IvanGoncharov** [comment]
> What do you mean by input types are duck typed?

Input data is validated based on their shape not on type information.
The idea here is that inputs are just data (often in serialized as JSON) that doesn't connected to the server's types. That's why we can't have a true polymorphism in input data and some other features that output types have.

**Comment by IvanGoncharov** [comment]
@raderio It's a design decision to have separate input and output types it has a lot of benefits but also it definitely has its cons.
This repo is intended for submitting a concrete proposal for the spec.
Please formulate a proposal that is compatible to all [GraphQL guiding principles](https://github.com/facebook/graphql/blob/master/CONTRIBUTING.md#guiding-principles) including:
> Backwards compatibility

If you interested in asking question:
> Have a question? Find community resources at graphql.org/community
