### ISSUE TITLE
Are default values for parameters valid?

### ISSUE THREAD

**Issue by kevin-lindsay-1** [facebook/graphql#551]
Hello, just wondering if something like this in my schema is valid, as I can see that applying default **arguments** is normal, but I'm having trouble determining in the spec if default **parameters** are normal. All of the cases I can see in the spec seem to be related to queries as opposed to schemas.

For example, a schema such as this:
```
type Query {
  thing(size: Int = 20): Thing
}
```
Which would enable a query like this:
```
{
  thing
}
```
Which is equivalent to:
```
{
  thing(size: 20)
}
```

**Comment by langpavel** [comment]
Yes, it is valid

**Comment by IvanGoncharov** [comment]
@kevin-lindsay-1 Yes, it valid. You can see it in language diagram:
https://facebook.github.io/graphql/June2018/#sec-Field-Arguments
![image](https://user-images.githubusercontent.com/8336157/51432765-da29bb80-1c45-11e9-81c5-b32da0fde5c1.png)
