### ISSUE TITLE
Add these to GraphQL Specification

### ISSUE THREAD

**Issue by guledali** [facebook/graphql#563]
Things that which will be part of graphql spec in the future

1. Way of handling file-uploads this is a big deal how to you do it 
https://blog.apollographql.com/file-uploads-with-apollo-server-2-0-5db2f3f60675

2. Authentication 

3. Authorization/permission 
https://www.youtube.com/watch?v=4_Bcw7BULC8&t=635s

**Comment by IvanGoncharov** [comment]
> 2\. Authentication
> 3\. Authorization/permission

Are not in a scope of this spec, please see:
https://graphql.org/learn/authorization/

> 1. Way of handling file-uploads this is a big deal how to you do it

GraphQL doesn't specify HTTP semantics of request/response and doesn't have a notion of files.
