### ISSUE TITLE
best practice for returning data

### ISSUE THREAD

**Issue by jsina** [facebook/graphql#565]
We have a lot of mutation in our service that all of these return the same type of response like there:

```
export default new GraphQLObjectType({
  name: 'MessageResponse',
  fields: () => ({
    message: {
      type: GraphQLString,
    },
  }),
});

```
My question is could I return this type for all of these mutations as a best practice or I have to create single type for each of those mutations?

**Comment by IvanGoncharov** [comment]
@jsina This repo is intended solely for GraphQL specification issues/proposal.
Please use StackOverflow or other community resources to ask about best practices.

P.S. My personal opinion is to have separate types since it will allow you to extend responses independently in the future.
