### ISSUE TITLE
Returning with lists

### ISSUE THREAD

**Issue by gergelyke** [facebook/graphql#59]
One thing is not clear - how should it be handled if the result is an array *(like users, where age > 40)* ?  Should all query return with a `GraphQL list` type, or how do you make a difference?

**Comment by tristanz** [comment]
@gergelyke It sounds like you should just return a `GraphQLList`.  You'd query with:
```
{
  users(olderThan: 40) {
    name
  }
}
```

**Comment by leebyron** [comment]
Correct, returning a List type is exactly how you should handle a field like that.
