### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ghost** [facebook/graphql#71]
Hello, everybody there! At first, I want to say thanks to you guys, who invent this small, but powerful query language.

But the main article of this issue, that the license that apply to this specification is not fit this kind of things, I think, that `BSD-3-Clause` license better to apply to the source code, but the specification should be licensed with Creative Common License.

[Creative Common License Attribution 4.0 Internation](https://creativecommons.org/licenses/by/4.0/), I think, is better.

Thanks!

**Comment by leebyron** [comment]
Thanks for the suggestion - I'll forward this to someone on our team who knows more about licensing.

**Comment by leebyron** [comment]
Closing this: after discussing with folks in the know, they decided it was best to continue to use a software license for this (even though it's a little bit weird).
