### ISSUE TITLE
Syntax highlighting for common IDEs

### ISSUE THREAD

**Issue by leebyron** [facebook/graphql#79]
This would be a great task to claim for an aspiring contributor.

**Comment by rmosolgo** [comment]
🎬 take 1 for Atom https://atom.io/packages/language-graphql

syntax only, looking forward to trying autocomplete :)

**Comment by wangyanxing** [comment]
Since I guess lots of people are using GraphGL for Android projects, is it a good idea to make a IntelliJ plugin?

**Comment by leebyron** [comment]
IntelliJ would be great

**Comment by wangyanxing** [comment]
On my way

**Comment by Gregoor** [comment]
I finished a basic version:
https://github.com/Gregoor/graphql-intellij-plugin

@leebyron: Is it possible that the spec is a bit incomplete in respect to type definitions starting with 'input'? But the grammar at the end was extremly helpful, thanks for that!

**Comment by kevinSuttle** [comment]
Looks like @devknoll is on it. 
https://twitter.com/devknoll/status/666469020976066560
https://twitter.com/devknoll/status/666476905739108352 

![image](https://cloud.githubusercontent.com/assets/95672/11349068/3bb1e304-91f8-11e5-88cc-d2278d02c6b0.png)

**Comment by jimkyndemeyer** [comment]
I've created a GraphQL plugin for IntelliJ IDEA and WebStorm that relies on the JavaScript reference implementation. It provides roughly the same features as Graph*i*QL, including schema-aware completion, error highlighting, and in-editor schema documentation:

https://github.com/jimkyndemeyer/js-graphql-intellij-plugin

The integration between the Java-based plugin and the reference implementation JavaScript parser is available as a Node.js based language service:

https://github.com/jimkyndemeyer/js-graphql-language-service

It might prove useful for enabling GraphQL language features in other IDEs, much like the TypeScript language service did for Sublime and Atom.

**Comment by Gregoor** [comment]
Awesome, that looks way better than what I did :) I'll try it, as soon as it is approved. Any idea how I can help the ~100 downloaders of my plugin migrate to your plugin?

**Comment by jimkyndemeyer** [comment]
@Gregoor A notification should do the trick :) How long did it take to get your plugin approved?

In case you want early access to the plugin, it can be downloaded from https://dl.dropboxusercontent.com/u/12996502/js-graphql-intellij-plugin/1.0.0/js-graphql-intellij-plugin.jar

Just add it using "Install plugin from disk..."

**Comment by Gregoor** [comment]
I think the approval process is bound to their 9-5 work cycle (in the czech republic). At least that's the feeling I got.

Thanks for the direct link.

**Comment by jparise** [comment]
I started on a Vim plugin: https://github.com/jparise/vim-graphql

It still needs work but handles file detection, syntax highlighting, and folding pretty well so far.

**Comment by abdulhannanali** [comment]
Can some one make a graphql package for lovely sublime text? :smile:

**Comment by syrusakbary** [comment]
@abdulhannanali I just released a GraphQL package for Sublime Text.
https://packagecontrol.io/packages/GraphQL

Right now is just a syntax highlighter, but we plan to add autocompletion and almost all the capabilities we have with GraphiQL.
Source code: https://github.com/graphql-python/GraphQL-SublimeText

**Comment by nicolaslopezj** [comment]
Autocomplete and lint from a GraphQL endpoint in atom.

https://github.com/nicolaslopezj/atom-graphql-autocomplete

<img width="649" alt="example" src="https://cloud.githubusercontent.com/assets/2042567/20637990/4c0f0320-b377-11e6-973a-d6cdd0220a29.png">

**Comment by jimkyndemeyer** [comment]
@nicolaslopezj That's great news. Would you consider using https://github.com/graphcool/graphql-config#method-2-configuration-via-graphqlrc-file to configure the endpoint?

**Comment by nicolaslopezj** [comment]
Yes I will!

**Comment by asiandrummer** [comment]
@nicolaslopezj - that looks cool :D I've been working to provide a language service interface for GraphQL that could be used across common IDEs. It'll also support firing up the GraphQL server to cache schema/fragment definitions/etc to be used for validation/autocomplete suggestions. The interface has methods to bring other common IDE features, such as hyperlink/outline views/and etc.

It's been developed and tested with Nuclide, but I thought this could be useful for Atom users as well - it'd be awesome if we can collaborate on making that happen!

**Comment by dncrews** [comment]
For @abdulhannanali and anyone else sad about the Sublime Text highlighter not working, I just released one that does. https://packagecontrol.io/packages/GraphQL

**Comment by abdulhannanali** [comment]
@dncrews Thanks a  lot @dncrews will surely help people using Sublime but I have long moved to [Visual Studio Code](https://code.visualstudio.com/) :heart:

**Comment by astorije** [comment]
Not really an IDE but since we're talking syntax highlighting, as I'm writing this comment:

- [Prism](http://prismjs.com/) **does** [support GraphQL](https://github.com/PrismJS/prism/pull/971)
- [Highlight.js](https://highlightjs.org/) **does not** [support GraphQL](https://github.com/isagalaev/highlight.js/issues/1471)

**Comment by borisdan** [comment]
A port of @jimkyndemeyer's GraphQL plugin for IntelliJ IDEA to work with Python  files in the JetBrains IDE would be amazing as well.
Currently, the Python client toolset is very lacking, and that is a pain that will interfere with GraphQL's growth.

**Comment by armetiz** [comment]
Could be awesome to see a plugin for PHPStorm !

**Comment by benjamindulau** [comment]
@jimkyndemeyer Awesome work! Your plugin changed my life in Javascript. Wondering though, do you think it would be hard work to make it also autocomplete queries in PHP Heredoc ?

Example:

```php
private function getQuery()
{

    $query = <<<'GQL'
query ProgrammesForHome($region: String, $travelStart: DateTime, $page: Int, $limit: Int) {
  programmes(region: $region, page: $page, limit: $limit) {
    total
    page
    limit
    edges {
      node {
        id
        name
        catchPhrase
        price {
          amount
          currency {
            code
          }
        }
        offers {
          id
        }
      }
    }
  }
}
GQL;

    return $query;
}
```

**Comment by leebyron** [comment]
Closing this generic issue since we now have pretty good coverage across many IDEs. Please open future language service issues on specific IDEs!
