### ISSUE TITLE
Custom Sorting

### ISSUE THREAD

**Issue by KyleAMathews** [facebook/graphql#8]
Didn't see anything in the spec about this. I assume it's coming?

**Comment by devknoll** [comment]
I believe @leebyron touched on this in his talk at ReactEurope. The gist of it is that you would expose the type of sorting that you want through field arguments.

I believe the example was something like:
```
{
  user(id: 4) {
    events(first: 1, order: IMPORTANT) {
      ...
    }
  }
}
```

**Comment by KyleAMathews** [comment]
Cool! Seems very reasonable.

**Comment by leebyron** [comment]
Thanks, @devknoll. Right on point. A field argument like `order` or `orderBy` means as much to GraphQL as `fooBar`. It's just a key/value pair that gets provided to the underlying function.

In the example @devknoll provided, you might imagine the backing function looking something like:

```js
function (user, { first, order }) {
  return doSomeWorkToGetEventsForUser(user, { limit: first, orderByKey: order });
}
```

Where that function does something interesting like a mongodb, sql, or parse query.

**Comment by gajus** [comment]
Would be nice if this somehow got standardised.
