### ISSUE TITLE
Documentation for mutation

### ISSUE THREAD

**Issue by pawsong** [facebook/graphql#81]
Thank you for this great work! The idea is awesome and README.md itself was interesting to me.

Is there any plan to write additional documentation for mutation on README.md?

**Comment by leebyron** [comment]
We're working on richer documentation which will definitely cover mutations further.

**Comment by leebyron** [comment]
Closing this individual task - but the work there continues, stay tuned!

**Comment by vitosamson** [comment]
Any progress on this? The spec makes hardly any mention of mutations - there's not even a section for it, it's only mentioned in passing a few times. I can't seem to find much information about mutations beyond very basic examples on the web either.

**Comment by StingyJack** [comment]
Almost 5 years later and the spec and most websites/tutorials still lack any reasonable example of a common "UPSERT/MERGE" mutation. Retrieval queries on the contrary have a plethora of examples, but they do no good without data in the system. Its like mutations are some kind of closely guarded secret.
