### ISSUE TITLE
sentence is not complete

### ISSUE THREAD

**Issue by wanghaisheng** [facebook/graphql#84]
in section 5 ### Field Selections on Objects, Interfaces, and Unions Types,
" Because fields are not declared on unions, direct field selection on union-typed selection set. This is true even if concrete implementors of the union define the fieldName."
what does "direct field selection on union-typed selection set." mean?

**Comment by leebyron** [comment]
Thanks for pointing this out! I just re-wrote this section to be more clear, I hope it helps.

**Comment by wanghaisheng** [comment]
thx for that
