### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by ronag** [facebook/graphql#86]
We need a way to listen to changes performed by someone else than the local client in order to build true real-time apps based on GraphQL. Similar to how Firebase and Meteor work.

I know this is being discussed on Slack but a proper ticket is missing.

**Comment by OlegIlyenko** [comment]
I made a small write-up about my thought on a GraphQL subscription mechanism:

https://gist.github.com/OlegIlyenko/a5a9ab1b000ba0b5b1ad

Any comments and thoughts on this idea are appreciated :)

**Comment by zuhair-naqvi** [comment]
+1

**Comment by leebyron** [comment]
Just wanted to add that a blog post was written on this topic as well: http://graphql.org/blog/subscriptions-in-graphql-and-relay/

Subscriptions is one piece of a larger topic of live data and asynchronicity that we plan on covering in the future with GraphQL. There are already experiments underway to better understand what the right decisions will be.

**Comment by leebyron** [comment]
Closing this aging issue since Subscriptions are captured in spec
