### ISSUE TITLE
Querying content with different priorities

### ISSUE THREAD

**Issue by luisobo** [facebook/graphql#94]
Hi,

With GraphQL (and relay) there is the potential of fetching the data for an entire screen in one query. This is great because it is simple but sometimes (if not most of the times) you want to grab the main content first (article content) and then grab the surroundings (related content, comments, stats of the article, etc) to improve the user experience.

Of course there is the option of making two separate GraphQL queries but, since the idea (especially with relay) seems to be having everything declarative, I'd rather avoid this option.

I'm wondering if there is a way of doing this. If not, it may be interesting to consider this use case, maybe in conjunction with subscriptions (give me the article content now and send me the rest once it is computed?)

Thanks for your time.

**Comment by fson** [comment]
These are called "deferred fragments" and they are used internally at Facebook, but the open source specification for them is yet to be developed. See: https://github.com/facebook/relay/issues/288

**Comment by luisobo** [comment]
uuuh, interesting. Thank you!
